/**
 * @module e2eTestIds
 * @description Centralized data-testid constants for Playwright E2E automation.
 *              Treat these as a public TestID API — keep values stable across releases.
 *
 * Key exports: E2E_TESTIDS
 */
// Stable `data-testid` strings used by E2E runners.
// Keep these values stable; treat them as a public "TestID API" for Playwright.

export const E2E_TESTIDS = Object.freeze({
  // -----------------------------------------
  // Navigation + Page Roots (full-app E2E)
  // -----------------------------------------
  NAV_HOME: 'ce-nav-home',
  NAV_SURVEYS: 'ce-nav-surveys',
  NAV_QUESTIONS: 'ce-nav-questions',
  NAV_SBTS: 'ce-nav-sbts',
  NAV_COMPARE: 'ce-nav-compare',
  NAV_BOOKMARKS: 'ce-nav-bookmarks',
  NAV_DOCS: 'ce-nav-docs',
  NAV_ABOUT: 'ce-nav-about',
  NAV_POSTS: 'ce-nav-posts',
  NAV_ADMIN: 'ce-nav-admin',
  NAV_SESSION: 'ce-nav-session',
  NAV_SESSION_DOCS: 'ce-nav-session-docs',
  NAV_SESSION_WIZARD: 'ce-nav-session-wizard',
  NAV_ATLAS: 'ce-nav-atlas',
  NAV_MATRIX: 'ce-nav-matrix',
  NAV_AGENT: 'ce-nav-agent',
  FOOTER_START_BUTTON: 'ce-footer-start-button',
  FOOTER_START_MENU: 'ce-footer-start-menu',
  ACCOUNT_LOGIN_BUTTON: 'ce-account-login-button',

  PAGE_HOME_ROOT: 'ce-page-home-root',
  PAGE_SURVEYS_ROOT: 'ce-page-surveys-root',
  PAGE_QUESTIONS_ROOT: 'ce-page-questions-root',
  PAGE_SBTS_ROOT: 'ce-page-sbts-root',
  PAGE_SBT_ROOT: 'ce-page-sbt-root',
  PAGE_COMPARE_ROOT: 'ce-page-compare-root',
  PAGE_BOOKMARKS_ROOT: 'ce-page-bookmarks-root',
  PAGE_DOCS_ROOT: 'ce-page-docs-root',
  DOCS_GITHUB_LINK: 'ce-docs-github-link',
  DOCS_SESSION_CONTEXT: 'ce-docs-session-context',
  DOCS_SESSION_CONTRACTS_GROUP: 'ce-docs-session-contracts-group',
  DOCS_CONTRACT_SESSION_SELECTOR: 'ce-docs-contract-session-selector',
  PAGE_ABOUT_ROOT: 'ce-page-about-root',
  PAGE_POSTS_ROOT: 'ce-page-posts-root',
  PAGE_BENCHMARKS_ROOT: 'ce-page-benchmarks-root',
  PAGE_ADMIN_ROOT: 'ce-page-admin-root',
  PAGE_SPONSOR_ROOT: 'ce-page-sponsor-root',
  PAGE_SESSION_ROOT: 'ce-page-session-root',
  PAGE_SESSION_DOCS_ROOT: 'ce-page-session-docs-root',
  PAGE_SESSION_WIZARD_ROOT: 'ce-page-session-wizard-root',
  SESSION_TELEGRAM_ONLY_NOTICE: 'ce-session-telegram-only-notice',
  SESSION_LOADING_SKELETON: 'ce-session-loading-skeleton',
  PAGE_ATLAS_ROOT: 'ce-page-atlas-root',
  PAGE_MATRIX_ROOT: 'ce-page-matrix-root',
  PAGE_AGENT_ROOT: 'ce-page-agent-root',
  PAGE_DEBATE_ROOT: 'ce-page-debate-root',
  DEBATE_VIEW_MODE: 'ce-debate-view-mode',
  ATLAS_NODE: 'ce-atlas-node',
  ATLAS_TITLE_ACTION: 'ce-atlas-title-action',
  ATLAS_HISTORICAL_CASE_CARD: 'ce-atlas-historical-case-card',
  ATLAS_HISTORICAL_CASE_EXPAND: 'ce-atlas-historical-case-expand',
  ATLAS_HISTORICAL_CASE_DETAIL: 'ce-atlas-historical-case-detail',
  ATLAS_HISTORICAL_CASE_PATCH_CARD: 'ce-atlas-historical-case-patch-card',

  // -----------------------------------------
  // AI tools/pages
  // -----------------------------------------
  COMPARE_ADDRESS_A: 'ce-compare-address-a',
  COMPARE_ADDRESS_B: 'ce-compare-address-b',
  COMPARE_ADD_ADDRESS: 'ce-compare-add-address',
  COMPARE_RUN: 'ce-compare-run',
  COMPARE_RESULT: 'ce-compare-result',
  COMPARE_AGREEMENTS: 'ce-compare-agreements',
  COMPARE_DISAGREEMENTS: 'ce-compare-disagreements',

  POLIS_REPORT_ROOT: 'ce-polis-report-root',
  POLIS_REPORT_LOADING_PROGRESS: 'ce-polis-report-loading-progress',
  POLIS_SETTINGS_TOGGLE: 'ce-polis-settings-toggle',
  POLIS_DEMO_DATA_TOGGLE: 'ce-polis-demo-data-toggle',
  POLIS_ANALYZE_CLUSTERS: 'ce-polis-analyze-clusters',
  POLIS_CLUSTER_ANALYSIS: 'ce-polis-cluster-analysis',
  TOOL_EXPLORER_DATA_ADD: 'ce-tool-explorer-data-add',
  TOOL_EXPLORER_DATA_VIEW: 'ce-tool-explorer-data-view',
  DATABASE_VIEW_DEMO_TOGGLE: 'ce-database-view-demo-toggle',
  DATABASE_VIEW_PANEL: 'ce-database-view-panel',
  DATABASE_PHOTO_SOURCE_CARD: 'ce-database-photo-source-card',
  DATABASE_PHOTO_SOURCE_PREVIEW: 'ce-database-photo-source-preview',
  DATABASE_PHOTO_SOURCE_ANALYSIS_TOGGLE: 'ce-database-photo-source-analysis-toggle',
  DATABASE_PHOTO_SOURCE_ANALYSIS_BODY: 'ce-database-photo-source-analysis-body',
  DATABASE_TITLE_INPUT: 'ce-database-title-input',
  DATABASE_ADD_LIBRARY_BUTTON: 'ce-database-add-library-button',
  DATABASE_LIBRARY_ANALYZE_TOGGLE: 'ce-database-library-analyze-toggle',
  DATABASE_IMAGE_CHOOSER: 'ce-database-image-chooser',
  DATABASE_IMAGE_PASTE: 'ce-database-image-paste',
  DATABASE_IMAGE_UPLOAD: 'ce-database-image-upload',
  DATABASE_IMAGE_FILE_INPUT: 'ce-database-image-file-input',
  DATABASE_SAVE_DOCS_TOGGLE: 'ce-database-save-docs-toggle',
  DATABASE_SAVE_DOCS_AUDIENCE_BUTTON: 'ce-database-save-docs-audience-button',
  DATABASE_SAVE_DOCS_AUDIENCE_MENU: 'ce-database-save-docs-audience-menu',
  DATABASE_SAVE_DOCS_AUDIENCE_SELF: 'ce-database-save-docs-audience-self',
  DATABASE_SAVE_DOCS_AUDIENCE_SESSION: 'ce-database-save-docs-audience-session',
  DATABASE_QUESTION_COUNT_VALUE: 'ce-database-question-count-value',
  DATABASE_QUESTION_COUNT_DECREMENT: 'ce-database-question-count-decrement',
  DATABASE_QUESTION_COUNT_INCREMENT: 'ce-database-question-count-increment',

  SESSION_RESULTS_TOGGLE: 'ce-session-results-toggle',
  SESSION_GROUPS_TOGGLE: 'ce-session-groups-toggle',
  SESSION_ADVANCED_ONCHAIN_ACCESS_GATES: 'ce-session-advanced-onchain-access-gates',
  SESSION_GROUPS_UNAVAILABLE: 'ce-session-groups-unavailable',
  SESSION_GROUP_CREATION_POLICY_DENIED: 'ce-session-group-creation-policy-denied',
  SESSION_WORKER_PARTICIPANT_GROUP_CREATE: 'ce-session-worker-participant-group-create',
  SESSION_WORKER_PARTICIPANT_GROUP_LABEL: 'ce-session-worker-participant-group-label',
  SESSION_WORKER_PARTICIPANT_GROUP_SUBMIT: 'ce-session-worker-participant-group-submit',
  SURVEY_FILTER_TOGGLE: 'ce-survey-filter-toggle',
  // Wallet display (for E2E assertions)
  WALLET_DISPLAY: 'ce-wallet-display',

  // Admin page
  ADMIN_SESSION_SELECT: 'ce-admin-session-select',
  ADMIN_GATE_MODE_SELECT: 'ce-admin-gate-mode-select',
  ADMIN_GATE_UPDATE_BUTTON: 'ce-admin-gate-update-button',
  ADMIN_GATE_STATUS: 'ce-admin-gate-status',
  ADMIN_NOT_ADMIN_WARNING: 'ce-admin-not-admin-warning',

  // Session Wizard (/session/new)
  WIZARD_SESSION_NAME: 'ce-wizard-session-name',
  WIZARD_SESSION_ENDS_AT: 'ce-wizard-session-ends-at',
  WIZARD_SESSION_INFO: 'ce-wizard-session-info',
  WIZARD_SESSION_COLOR_SCHEME: 'ce-wizard-session-color-scheme',
  WIZARD_SESSION_COLOR_PREVIEW: 'ce-wizard-session-color-preview',
  SETTINGS_THEME: 'ce-settings-theme',
  WIZARD_SESSION_HEADER_INLINE_BAR: 'ce-wizard-session-header-inline-bar',
  WIZARD_SESSION_HEADER_URL_TOGGLE: 'ce-wizard-session-header-url-toggle',
  WIZARD_SESSION_HEADER_PASTE: 'ce-wizard-session-header-paste',
  WIZARD_SESSION_HEADER_URL: 'ce-wizard-session-header-url',
  WIZARD_SLUG: 'ce-wizard-slug',
  WIZARD_SLUG_AVAILABLE: 'ce-wizard-slug-available',
  WIZARD_SLUG_TAKEN: 'ce-wizard-slug-taken',
  WIZARD_MODE_NORMAL: 'ce-wizard-mode-normal',
  WIZARD_MODE_ADVANCED: 'ce-wizard-customize',
  WIZARD_GROUP_CREATION_POLICY: 'ce-wizard-group-creation-policy',
  WIZARD_METADATA_PANEL_TOGGLE: 'ce-wizard-metadata-panel-toggle',
  WIZARD_WORKER_MODE_TOGGLE: 'ce-wizard-worker-mode-toggle',
  WIZARD_WORKER_MODE_BUTTON: 'ce-wizard-worker-mode-button',
  WIZARD_WORKER_PANEL_TOGGLE: 'ce-wizard-worker-panel-toggle',
  WIZARD_WORKER_SECRETS_REQUIRE_PAY: 'ce-wizard-worker-secrets-require-pay',
  WIZARD_EMBEDDED_DEPLOY_HELPER_ENABLED: 'ce-wizard-embedded-deploy-helper-enabled',
  WIZARD_ADD_GATE: 'ce-wizard-add-gate',
  WIZARD_CREATE_SBT: 'ce-wizard-create-sbt',
  WIZARD_PENDING_SBT: 'ce-wizard-pending-sbt',
  WIZARD_RESOURCE_CARD: 'ce-wizard-resource-card',
  WIZARD_SECRET_OPENAI_KEY: 'ce-wizard-secret-openai-key',
  WIZARD_SECRET_ANTHROPIC_KEY: 'ce-wizard-secret-anthropic-key',
  WIZARD_SECRET_OPENROUTER_KEY: 'ce-wizard-secret-openrouter-key',
  WIZARD_SECRET_ARWEAVE_JWK: 'ce-wizard-secret-arweave-jwk',
  WIZARD_SECRET_FAUCET_PRIVATE_KEY: 'ce-wizard-secret-faucet-private-key',
  WIZARD_SECRET_LIT_API_BASE: 'ce-wizard-secret-lit-api-base',
  WIZARD_SECRET_LIT_GROUP_ID: 'ce-wizard-secret-lit-group-id',
  WIZARD_SECRET_LIT_PKP_ID: 'ce-wizard-secret-lit-pkp-id',
  WIZARD_SECRET_LIT_ACTION_CID: 'ce-wizard-secret-lit-action-cid',
  WIZARD_SECRET_LIT_ACCOUNT_API_KEY: 'ce-wizard-secret-lit-account-api-key',
  WIZARD_SECRET_LIT_USAGE_API_KEY: 'ce-wizard-secret-lit-usage-api-key',
  WIZARD_SECRET_LIT_PAYER_PRIVATE_KEY: 'ce-wizard-secret-lit-payer-private-key',
  WIZARD_SECRET_LIT_PAYER_ADDRESS: 'ce-wizard-secret-lit-payer-address',
  WIZARD_COPY_LIT_PAYER_ADDRESS: 'ce-wizard-copy-lit-payer-address',
  WIZARD_DEPLOY_HELPER_URL: 'ce-wizard-deploy-helper-url',
  WIZARD_CLOUDFLARE_TOKEN_ONBOARDING_LINK: 'ce-wizard-cloudflare-token-onboarding-link',
  WIZARD_CLOUDFLARE_TOKEN_CREATE_LINK: 'ce-wizard-cloudflare-token-create-link',
  WIZARD_CLOUDFLARE_API_TOKEN: 'ce-wizard-cloudflare-api-token',
  WIZARD_CLOUDFLARE_NATIVE_GENERATE: 'ce-wizard-cloudflare-native-generate',
  WIZARD_CLOUDFLARE_NATIVE_DEPLOY: 'ce-wizard-cloudflare-native-deploy',
  WIZARD_CLOUDFLARE_NATIVE_TOKEN_HMAC: 'ce-wizard-cloudflare-native-token-hmac',
  WIZARD_CLOUDFLARE_NATIVE_STORAGE_KEK: 'ce-wizard-cloudflare-native-storage-kek',
  WIZARD_CLOUDFLARE_NATIVE_SESSION_SLUG: 'ce-wizard-cloudflare-native-session-slug',
  WIZARD_CLOUDFLARE_NATIVE_ADMIN_ADDRESS: 'ce-wizard-cloudflare-native-admin-address',
  WIZARD_BUNDLE_MODE_UPLOAD: 'ce-wizard-bundle-mode-upload',
  WIZARD_BUNDLE_MODE_URL: 'ce-wizard-bundle-mode-url',
  WIZARD_BUNDLE_FILE_INPUT: 'ce-wizard-bundle-file-input',
  WIZARD_CLEAR_BUNDLE_FILE_DEPLOY: 'ce-session-wizard-clear-bundle-file-deploy',
  WIZARD_CLEAR_BUNDLE_FILE_PUBLISH: 'ce-session-wizard-clear-bundle-file-publish',
  WIZARD_BUNDLE_URL: 'ce-wizard-bundle-url',
  WIZARD_BUNDLE_URL_OVERRIDE: 'ce-wizard-bundle-url-override',
  WIZARD_WORKER_NAME: 'ce-wizard-worker-name',
  WIZARD_DEPLOY_WORKER: 'ce-wizard-deploy-worker',
  WIZARD_DEPLOY_STATUS: 'ce-wizard-deploy-status',
  WIZARD_WORKER_URL: 'ce-wizard-worker-url',
  WIZARD_SPONSORED_STATUS: 'ce-wizard-sponsored-status',
  WIZARD_SPONSORED_KEY_INPUT: 'ce-wizard-sponsored-key-input',
  WIZARD_SPONSORED_KEY_APPLY: 'ce-wizard-sponsored-key-apply',
  WIZARD_PUBLISH: 'ce-wizard-publish',
  WIZARD_METADATA_URI: 'ce-wizard-metadata-uri',
  WIZARD_ADMIN_URL: 'ce-wizard-admin-url',
  WIZARD_REGISTER_TX: 'ce-wizard-register-tx',

  // Sponsor page
  SPONSOR_WORKER_URL_TOGGLE: 'ce-sponsor-worker-url-toggle',
  SPONSOR_WORKER_URL: 'ce-sponsor-worker-url',
  SPONSOR_CREATE: 'ce-sponsor-create',
  SPONSOR_STATUS: 'ce-sponsor-status',
  SPONSOR_SHARE_URL: 'ce-sponsor-share-url',
  SPONSOR_SHARE_KEY: 'ce-sponsor-share-key',
  SPONSOR_TX_ID: 'ce-sponsor-tx-id',

  // Agent page UI
  AGENT_ACTIONS: 'ce-agent-actions',
  AGENT_RUN: 'ce-agent-run',
  AGENT_STEP: 'ce-agent-step',
  AGENT_LOG: 'ce-agent-log',

  // SurveyTool (answering/responding)
  SURVEY_DECRYPT_PROMPT: 'ce-survey-decrypt-prompt',
  SURVEY_DECRYPT_PROMPT_NOTICE: 'ce-survey-decrypt-prompt-notice',
  SURVEY_GATED_PROMPT_NOTICE: 'ce-survey-gated-prompt-notice',
  SURVEY_LOCKED_BANNER: 'ce-survey-locked-banner',
  SURVEY_LOCKED_BANNER_CARET: 'ce-survey-locked-banner-caret',
  SURVEY_LOCKED_DECRYPT: 'ce-survey-locked-decrypt',
  SURVEY_ANSWER_INPUT: 'ce-survey-answer-input',
  SURVEY_TOOLBAR: 'ce-survey-toolbar',
  SURVEY_SUBMIT: 'ce-survey-submit',
  SURVEY_CREATE_TOGGLE: 'ce-survey-create-toggle',
  SURVEY_CREATE_TOGGLE_PILE: 'ce-survey-create-toggle-pile',
  SURVEY_VIEW_ALL: 'ce-survey-view-all',
  SURVEY_PILE_HOLOGRAM_TOGGLE: 'ce-survey-pile-hologram-toggle',
  SURVEY_PILE_HOLOGRAM_PANEL: 'ce-survey-pile-hologram-panel',
  SESSION_LISTENING_TOGGLE: 'ce-session-listening-toggle',
  SESSION_LISTENING_PANEL: 'ce-session-listening-panel',
  SESSION_LISTENING_START: 'ce-session-listening-start',
  SESSION_LISTENING_STOP: 'ce-session-listening-stop',
  SESSION_LISTENING_CLEAR: 'ce-session-listening-clear',
  SESSION_LISTENING_TRANSCRIPT_DETAILS: 'ce-session-listening-transcript-details',
  SESSION_LISTENING_TRANSCRIPT: 'ce-session-listening-transcript',
  SESSION_LISTENING_GENERATE: 'ce-session-listening-generate',
  SESSION_LISTENING_SUGGESTIONS: 'ce-session-listening-suggestions',
  SURVEY_ADDITIONAL_TOGGLE: 'ce-survey-additional-toggle',
  SURVEY_ADDITIONAL_INPUT: 'ce-survey-additional-input',
  SURVEY_ADDITIONAL_LOCK: 'ce-survey-additional-lock',
  SURVEY_ANSWER_LOCK: 'ce-survey-answer-lock',
  SURVEY_LOCK_AUDIENCE_NONE: 'ce-survey-lock-audience-none',
  SURVEY_LOCK_AUDIENCE_SELF: 'ce-survey-lock-audience-self',
  SURVEY_LOCK_AUDIENCE_GATE: 'ce-survey-lock-audience-gate',
  SURVEY_LOCK_AUDIENCE_FOLLOW: 'ce-survey-lock-audience-follow',
  SURVEY_EXISTING_RESPONSE_NOTICE: 'ce-survey-existing-response-notice',
  SURVEY_SUBMITTED_INDICATOR: 'ce-survey-submitted-indicator',
  SURVEY_START_FRESH: 'ce-survey-start-fresh',
  SURVEY_DECRYPT_EDIT_ALL: 'ce-survey-decrypt-edit-all',
  SURVEY_EXIT_EDITING: 'ce-survey-exit-editing',
  SURVEY_QUESTIONS_TOGGLE: 'ce-survey-questions-toggle',
  SURVEY_QUESTIONS_ENCRYPTED_COUNT: 'ce-survey-questions-encrypted-count',
  QUESTION_FILTER_MODAL: 'ce-question-filter-modal',
  QUESTION_FILTER_SECTION_AI: 'ce-question-filter-section-ai',
  QUESTION_FILTER_SECTION_SBT: 'ce-question-filter-section-sbt',
  QUESTION_FILTER_AI_QUERY: 'ce-question-filter-ai-query',
  QUESTION_FILTER_AI_TOP_N: 'ce-question-filter-ai-top-n',
  QUESTION_FILTER_AI_APPLY: 'ce-question-filter-ai-apply',
  QUESTION_FILTER_CLEAR_ALL: 'ce-question-filter-clear-all',

  // CreateQuestionsAndSurveys (authoring)
  CREATE_PANEL: 'ce-create-panel',
  CREATE_MODE_SWITCH: 'ce-create-mode-switch',
  CREATE_CLEAR: 'ce-create-clear',
  CREATE_TITLE: 'ce-create-title',
  CREATE_QUESTION: 'ce-create-question',
  CREATE_QUESTION_PROMPT: 'ce-create-question-prompt',
  CREATE_QUESTION_TAG_INPUT: 'ce-create-question-tag-input',
  CREATE_QUESTION_ADD_TAG: 'ce-create-question-add-tag',
  CREATE_QUESTION_ADD_OPTION: 'ce-create-question-add-option',
  CREATE_QUESTION_SINGLE_SELECT: 'ce-create-question-single-select',
  CREATE_SUBMIT: 'ce-create-submit',
  CREATE_SUCCESS: 'ce-create-success',
  CREATE_UPLOADED_QUESTIONS: 'ce-create-uploaded-questions',
  CREATE_UPLOADED_QUESTION: 'ce-create-uploaded-question',

  // Gate lock popover
  GATE_LOCK: 'ce-gate-lock',
  GATE_LOCK_BUTTON: 'ce-gate-lock-button',
  GATE_LOCK_POPOVER: 'ce-gate-lock-popover',
  GATE_LOCK_ROW: 'ce-gate-lock-row',
  GATE_LOCK_CHECKBOX: 'ce-gate-lock-checkbox',

  // Session OnePageSession
  SESSION_PILE_BACK: 'ce-session-pile-back',
  SESSION_QUESTIONS_FULL_HEADER: 'ce-session-questions-full-header',
  SESSION_AUTO_MINT_LOGIN_BANNER: 'ce-session-auto-mint-login-banner',
  SESSION_AUTO_MINT_COUNTDOWN: 'ce-session-auto-mint-countdown',
  SESSION_AUTO_MINT_STATUS: 'ce-session-auto-mint-status',

  // Doc Library
  DOC_PANEL: 'ce-doc-panel',
  DOC_TITLE: 'ce-doc-title',
  DOC_REFRESH: 'ce-doc-refresh',
  DOC_UPLOAD_FILE_INPUT: 'ce-doc-upload-file-input',
  DOC_UPLOAD_FILE_BUTTON: 'ce-doc-upload-file-button',
  DOC_URL_INPUT: 'ce-doc-url-input',
  DOC_URL_TITLE_INPUT: 'ce-doc-url-title-input',
  DOC_URL_ADD_BUTTON: 'ce-doc-url-add-button',
  DOC_LOCK_TOGGLE: 'ce-doc-lock-toggle',
  DOC_AUDIENCE_SESSION_GATE: 'ce-doc-audience-session-gate',
  DOC_AUDIENCE_CUSTOM: 'ce-doc-audience-custom',
  DOC_CUSTOM_SBT_INPUT: 'ce-doc-custom-sbt-input',
  DOC_CUSTOM_SBT_ADD: 'ce-doc-custom-sbt-add',
  DOC_CUSTOM_SBT_SELECTOR: 'ce-doc-custom-sbt-selector',
  DOC_CUSTOM_MODE_ANY: 'ce-doc-custom-mode-any',
  DOC_CUSTOM_MODE_ALL: 'ce-doc-custom-mode-all',
  DOC_ROW: 'ce-doc-row',
  DOC_ROW_IMAGE_PREVIEW: 'ce-doc-row-image-preview',
  DOC_ROW_VIEW: 'ce-doc-row-view',
  DOC_ROW_OPEN_ARWEAVE: 'ce-doc-row-open-arweave',
  DOC_VIEWER: 'ce-doc-viewer',
  DOC_VIEWER_TITLE: 'ce-doc-viewer-title',
  DOC_VIEWER_ERROR: 'ce-doc-viewer-error',
  DOC_VIEWER_DOWNLOAD: 'ce-doc-viewer-download',
  DOC_VIEWER_PDF: 'ce-doc-viewer-pdf',
  DOC_VIEWER_IMAGE: 'ce-doc-viewer-image',
  DOC_VIEWER_TEXT: 'ce-doc-viewer-text',

  // SingleQuestionResponse (decrypting previously submitted responses)
  ENCRYPTED_ANSWER_NOTICE: 'ce-encrypted-answer-notice',
  DECRYPT_ANSWER: 'ce-decrypt-answer',
  ENCRYPTED_ADDITIONAL_NOTICE: 'ce-encrypted-additional-notice',
  DECRYPT_ADDITIONAL: 'ce-decrypt-additional',

  // SBT selector controls
  SBT_SELECTOR_ROOT: 'ce-sbt-selector-root',
  SBT_SELECTOR_MANUAL_TOGGLE: 'ce-sbt-selector-manual-toggle',
  SBT_SELECTOR_MANUAL_INPUT: 'ce-sbt-selector-manual-input',
  SBT_SELECTOR_MANUAL_ADD: 'ce-sbt-selector-manual-add',
  SBT_SELECTOR_SELECTED: 'ce-sbt-selector-selected',
  SBT_SELECTOR_LOADING: 'ce-sbt-selector-loading',
  SBT_SELECTOR_LOADING_STATUS: 'ce-sbt-selector-loading-status',

  // CreateSBTGroup + SBTPage
  SBTS_CREATE_TOGGLE: 'ce-sbts-create-toggle',
  SBT_CREATE_NAME_INPUT: 'ce-sbt-create-name-input',
  SBT_CREATE_DESCRIPTION_INPUT: 'ce-sbt-create-description-input',
  SBT_CREATE_NAME_LOCK_ROW: 'ce-sbt-create-name-lock-row',
  SBT_CREATE_DESCRIPTION_LOCK_ROW: 'ce-sbt-create-description-lock-row',
  SBT_CREATE_IMAGE_LOCK_ROW: 'ce-sbt-create-image-lock-row',
  SBT_CREATE_DOCS_LOCK_ROW: 'ce-sbt-create-docs-lock-row',
  SBT_CREATE_TAGS_LOCK_ROW: 'ce-sbt-create-tags-lock-row',
  SBT_CREATE_IMAGE_FILE_INPUT: 'ce-sbt-create-image-file-input',
  SBT_CREATE_IMAGE_PASTE: 'ce-sbt-create-image-paste',
  SBT_CREATE_IMAGE_URL_INPUT: 'ce-sbt-create-image-url-input',
  SBT_CREATE_DOC_URL_INPUT: 'ce-sbt-create-doc-url-input',
  SBT_CREATE_DOC_URL_ADD: 'ce-sbt-create-doc-url-add',
  SBT_CREATE_TAG_INPUT: 'ce-sbt-create-tag-input',
  SBT_CREATE_TAG_ADD: 'ce-sbt-create-tag-add',
  SBT_CREATE_SECTION_HEADER: 'ce-sbt-create-section-header',
  SBT_CREATE_ERROR: 'ce-sbt-create-error',
  SBT_CREATE_PREDICTABLE_TOGGLE: 'ce-sbt-create-predictable-toggle',
  SBT_CREATE_PREDICTED_ADDRESS: 'ce-sbt-create-predicted-address',
  SBT_CREATE_SALT_INPUT: 'ce-sbt-create-salt-input',
  SBT_CREATE_SUBMIT: 'ce-sbt-create-submit',
  SBT_CREATE_SUCCESS: 'ce-sbt-create-success',
  SBT_CREATE_SUCCESS_PAGE_LINK: 'ce-sbt-create-success-page-link',
  SBT_CREATE_SUCCESS_ARWEAVE_LINK: 'ce-sbt-create-success-arweave-link',
  SBT_CREATE_OPEN_MINT_URL: 'ce-sbt-create-open-mint-url',
  SBT_PAGE_NAME: 'ce-sbt-page-name',
  SBT_PAGE_DESCRIPTION: 'ce-sbt-page-description',
  SBT_PAGE_IMAGE: 'ce-sbt-page-image',
  SBT_PAGE_OPEN_MINT_URL: 'ce-sbt-page-open-mint-url',
});
