import type { SectionDeriveMemo, UnknownRecord } from './userPageRuntimeTypes';

export const createUserPageSectionDeriveMemo = (): SectionDeriveMemo => ({
  survey: null,
  question: null,
  sbt: null,
});

export const createInitialUserPageState = (): UnknownRecord => ({
  viewAddress: '',
  surveyResponseInfo: [],
  surveyCreationInfo: [],
  questionCreationInfo: [],
  questionResponseInfo: [],
  detailedSurveyResponses: {},
  detailedQuestionResponses: {},
  userStats: {
    surveysResponded: 0,
    surveysCreated: 0,
    questionsResponded: 0,
    questionsCreated: 0,
    mostUniqueIdea: ' ... ',
    badgesReceived: 0,
    worryScore: 'x%',
    enthusiasmScore: 'y%',
    topTags: ['#cybersecurity', '#ubi', '#mechinterp'],
  },
  copied: false,
  collapseOpen: false,
  username: '',
  usernameError: '',
  isEditingUsername: false,
  bookmarked: false,
  sbtList: [],
  loadingSBTs: true,
  loadingSurveys: true,
  loadingQuestions: true,
  showAnalysisModal: false,
  aiAnalysis: '',
  analysisName: '',
  analysisDetails: '',
  analysisError: '',
  analyzing: false,
  aiAvailable: null,
  analysisElapsedMs: 0,
  analysisHistoricalFigure: '',
  analysisHistoricalReasoning: '',
  analysisServedFromCache: false,
  analysisCachedAt: null,
  showFullProfileModal: false,
  isSimulated: false,
  selectedTab: 'questions',
  expandedSurveyResponses: {},
  expandedSurveysCreated: {},
  showSectionSurveyResponsesOpen: true,
  showSectionSurveysCreatedOpen: true,
  showSectionQuestionResponsesOpen: true,
  showSectionQuestionsCreatedOpen: true,
  nicknameInput: '',
  isEditingNickname: false,
  isDeepScanning: false,
  hasUncertainUserData: false,
  hasUncertainSbtData: false,
  hasUncertainGateAccess: false,
  deepScanProgressTick: 0,
  deepScanTooltipLines: null,
  deepScanProgressRows: null,
});
