export type AnyRecord = Record<string, any>;

export type MainSiteProps = {
  fetchSessionState: (...args: any[]) => any;
  fetchAccount: (...args: any[]) => any;
  changeFocusedTab: (...args: any[]) => any;
  toggleLoginModal: (...args: any[]) => any;
  updateLoginInfo: (...args: any[]) => any;
  toggleDemoMode: (...args: any[]) => any;
  changeActiveSessionSlug: (...args: any[]) => any;
  profile?: AnyRecord;
  account?: string;
  provider?: string;
  network?: AnyRecord;
  sessionState?: AnyRecord;
  focusedTab?: number;
  loginComplete?: boolean;
  loginInProgress?: boolean;
  demoMode?: AnyRecord;
  demoSurfaceMode?: boolean | null;
  activeSessionSlug?: string;
  wagmiChainOptions?: any[];
  wagmiBlocknumber?: number;
  urlExtension?: AnyRecord;
  path?: string;
  nftCode?: string;
  urlPath?: string;
  firstVisit?: boolean;
  socket?: any;
  matchesContractAddress?: string;
  viewAddress?: string;
  [key: string]: any;
};

export type MainSiteState = {
  isSBTCacheReady: boolean;
  isSurveyCacheReady: boolean;
  isQuestionCacheReady: boolean;
  isResponsesCacheReady: boolean;
  isAllCachesReady: boolean;
  surveyCacheInitializationError: boolean;
  questionCacheInitializationError: boolean;
  cacheHasLoaded: boolean;
  sbtCacheRevision: number;
  sbtScanTick: number;
  sbtScanProgressBySlug: AnyRecord;
  sbtRealtimeCoverageBySlug: AnyRecord;
  questionResponsesNonce: number;
  sessionRegistryRevision: number;
  questionScanProgress: any | null;
  isScanningForGroup: any | null;
  scanFailedFor: any | null;
  scanErrorFor: any | null;
  scanErrorMessage: string;
  sbtDetailGroupSlug: string | null;
  sbtDetailAddress: string | null;
  litHooks: any | null;
  sessionInfoOverrides: AnyRecord;
  sessionNameOverrides: AnyRecord;
  sessionHeaderOverrides: AnyRecord;
  groupCredentials: AnyRecord;
  sessionPathResolutionNonce: number;
  isCacheManagerReady: boolean;
  [key: string]: any;
};
