import {
  AGENT_EXECUTION_POLICIES,
  AGENT_GRANT_SCOPES,
  AGENT_RISK_LEVELS,
} from './lifecycle.mjs';

export const AGENT_ACTION_STATUS = Object.freeze({
  IMPLEMENTED: 'implemented',
  CONTRACT_ONLY: 'contract_only',
  DEFERRED: 'deferred',
});

export const AGENT_ACTION_IDS = Object.freeze({
  READ_IDENTITY: 'agent.read.identity',
  READ_SESSIONS: 'agent.read.sessions',
  READ_QUESTIONS: 'agent.read.questions',
  DRAFT_RESPONSE: 'agent.response.draft',
  SUBMIT_RESPONSE_REQUEST: 'agent.response.submit_request',
  RESPONSE_DELEGATED_EXECUTE: 'agent.response.delegated_execute',
  DECRYPT_REQUEST: 'agent.decrypt.request',
  CONNECT_GRANT_REQUEST: 'agent.grant.connect_request',
  CONNECT_GRANT_READ: 'agent.grant.connect_read',
  CONNECT_GRANT_APPROVE: 'agent.grant.connect_approve',
  CONNECT_GRANT_DENY: 'agent.grant.connect_deny',
  GRANT_REVOKE: 'agent.grant.revoke',
  ACCOUNT_CREATE: 'agent.account.create',
  ACCOUNT_LINK_REQUEST: 'agent.account.link_request',
  WORKER_SETUP_STATUS: 'agent.worker_setup.status',
  WORKER_SETUP_ONBOARDING_CONFIG: 'agent.worker_setup.onboarding_config',
  QUESTION_GENERATION_REQUEST: 'agent.question.generate_request',
  SURVEY_AUTHORING_REQUEST: 'agent.survey.author_request',
  SBT_GROUP_DRAFT_REQUEST: 'agent.sbt_group.draft_request',
  SBT_GROUP_CREATE_REQUEST: 'agent.sbt_group.create_request',
  SBT_GROUP_SHARE_REQUEST: 'agent.sbt_group.share_request',
  SBT_GROUP_CLAIM_REQUEST: 'agent.sbt_group.claim_request',
  SESSION_CREATE_REQUEST: 'agent.session.create_request',
  SESSION_CONFIG_REQUEST: 'agent.session.config_request',
  DELIBERATIVE_STATEMENT_SIGNAL_REQUEST: 'agent.deliberation.statement_signal_request',
  DELIBERATIVE_STATEMENT_PROPOSAL_REQUEST: 'agent.deliberation.statement_proposal_request',
  DELIBERATIVE_STATEMENT_RANKING_REQUEST: 'agent.deliberation.statement_ranking_request',
});

const route = (method, path) => Object.freeze({ method, path });
const adapters = (telegram, openclaw) => Object.freeze({ telegram, openclaw });

const ACTION_INVENTORY_ENTRIES = [
  {
    actionId: AGENT_ACTION_IDS.READ_IDENTITY,
    family: 'read',
    route: route('GET', '/api/agent/me'),
    status: AGENT_ACTION_STATUS.IMPLEMENTED,
    requiredScopes: [AGENT_GRANT_SCOPES.READ],
    riskLevel: AGENT_RISK_LEVELS.READ,
    approvalBehavior: 'allowed_read',
    signingOrWorkerAuthority: 'none',
    adaptersMayCallDirectly: adapters(true, true),
  },
  {
    actionId: AGENT_ACTION_IDS.READ_SESSIONS,
    family: 'read',
    route: route('GET', '/api/agent/sessions'),
    status: AGENT_ACTION_STATUS.IMPLEMENTED,
    requiredScopes: [AGENT_GRANT_SCOPES.READ],
    riskLevel: AGENT_RISK_LEVELS.READ,
    approvalBehavior: 'allowed_read',
    signingOrWorkerAuthority: 'none',
    adaptersMayCallDirectly: adapters(true, true),
  },
  {
    actionId: AGENT_ACTION_IDS.READ_QUESTIONS,
    family: 'read',
    route: route('GET', '/api/agent/questions'),
    status: AGENT_ACTION_STATUS.IMPLEMENTED,
    requiredScopes: [AGENT_GRANT_SCOPES.READ],
    riskLevel: AGENT_RISK_LEVELS.READ,
    approvalBehavior: 'allowed_read',
    signingOrWorkerAuthority: 'none',
    adaptersMayCallDirectly: adapters(true, true),
  },
  {
    actionId: AGENT_ACTION_IDS.DRAFT_RESPONSE,
    family: 'response',
    route: route('POST', '/api/agent/responses/draft'),
    status: AGENT_ACTION_STATUS.IMPLEMENTED,
    requiredScopes: [AGENT_GRANT_SCOPES.DRAFT],
    riskLevel: AGENT_RISK_LEVELS.LOW,
    approvalBehavior: 'allowed_without_submission',
    signingOrWorkerAuthority: 'none',
    adaptersMayCallDirectly: adapters(true, true),
  },
  {
    actionId: AGENT_ACTION_IDS.SUBMIT_RESPONSE_REQUEST,
    family: 'response',
    route: route('POST', '/api/agent/responses/submit-request'),
    status: AGENT_ACTION_STATUS.IMPLEMENTED,
    requiredScopes: [AGENT_GRANT_SCOPES.SUBMIT_REQUEST],
    riskLevel: AGENT_RISK_LEVELS.MEDIUM,
    approvalBehavior: AGENT_EXECUTION_POLICIES.APPROVAL_REQUIRED,
    signingOrWorkerAuthority: 'may_require_ce_owned',
    adaptersMayCallDirectly: adapters(true, true),
  },
  {
    actionId: AGENT_ACTION_IDS.RESPONSE_DELEGATED_EXECUTE,
    family: 'response',
    route: route('POST', '/api/agent/responses/delegated-execute'),
    status: AGENT_ACTION_STATUS.CONTRACT_ONLY,
    requiredScopes: [AGENT_GRANT_SCOPES.DELEGATED_EXECUTE],
    riskLevel: AGENT_RISK_LEVELS.MEDIUM,
    approvalBehavior: AGENT_EXECUTION_POLICIES.SCOPED_DELEGATED_EXECUTE,
    signingOrWorkerAuthority: 'may_require_ce_owned',
    adaptersMayCallDirectly: adapters(true, true),
  },
  {
    actionId: AGENT_ACTION_IDS.DECRYPT_REQUEST,
    family: 'decrypt',
    route: route('POST', '/api/agent/decrypt/request'),
    status: AGENT_ACTION_STATUS.DEFERRED,
    requiredScopes: [AGENT_GRANT_SCOPES.DECRYPT_REQUEST],
    riskLevel: AGENT_RISK_LEVELS.HIGH,
    approvalBehavior: AGENT_EXECUTION_POLICIES.APPROVAL_REQUIRED,
    signingOrWorkerAuthority: 'may_require_ce_owned',
    adaptersMayCallDirectly: adapters(false, false),
  },
  {
    actionId: AGENT_ACTION_IDS.CONNECT_GRANT_REQUEST,
    family: 'grant',
    route: route('POST', '/api/agent/connect-requests'),
    status: AGENT_ACTION_STATUS.IMPLEMENTED,
    requiredScopes: [AGENT_GRANT_SCOPES.READ],
    riskLevel: AGENT_RISK_LEVELS.LOW,
    approvalBehavior: 'human_grant_approval_required',
    signingOrWorkerAuthority: 'none',
    adaptersMayCallDirectly: adapters(true, true),
  },
  {
    actionId: AGENT_ACTION_IDS.CONNECT_GRANT_READ,
    family: 'grant',
    route: route('GET', '/api/agent/connect-requests/:id'),
    status: AGENT_ACTION_STATUS.IMPLEMENTED,
    requiredScopes: [AGENT_GRANT_SCOPES.READ],
    riskLevel: AGENT_RISK_LEVELS.READ,
    approvalBehavior: 'side_effect_free_read',
    signingOrWorkerAuthority: 'none',
    adaptersMayCallDirectly: adapters(true, true),
  },
  {
    actionId: AGENT_ACTION_IDS.CONNECT_GRANT_APPROVE,
    family: 'grant',
    route: route('POST', '/api/agent/connect-requests/approve'),
    status: AGENT_ACTION_STATUS.IMPLEMENTED,
    requiredScopes: [AGENT_GRANT_SCOPES.REVOKE_GRANT],
    riskLevel: AGENT_RISK_LEVELS.MEDIUM,
    approvalBehavior: 'local_human_approval_only',
    signingOrWorkerAuthority: 'none',
    adaptersMayCallDirectly: adapters(false, false),
  },
  {
    actionId: AGENT_ACTION_IDS.CONNECT_GRANT_DENY,
    family: 'grant',
    route: route('POST', '/api/agent/connect-requests/deny'),
    status: AGENT_ACTION_STATUS.IMPLEMENTED,
    requiredScopes: [AGENT_GRANT_SCOPES.REVOKE_GRANT],
    riskLevel: AGENT_RISK_LEVELS.LOW,
    approvalBehavior: 'local_human_approval_only',
    signingOrWorkerAuthority: 'none',
    adaptersMayCallDirectly: adapters(false, false),
  },
  {
    actionId: AGENT_ACTION_IDS.GRANT_REVOKE,
    family: 'grant',
    route: route('POST', '/api/agent/grants/revoke'),
    status: AGENT_ACTION_STATUS.IMPLEMENTED,
    requiredScopes: [AGENT_GRANT_SCOPES.REVOKE_GRANT],
    riskLevel: AGENT_RISK_LEVELS.LOW,
    approvalBehavior: 'human_wallet_scoped',
    signingOrWorkerAuthority: 'none',
    adaptersMayCallDirectly: adapters(true, true),
  },
  {
    actionId: AGENT_ACTION_IDS.ACCOUNT_CREATE,
    family: 'account',
    route: route('POST', '/api/agent/accounts/create'),
    status: AGENT_ACTION_STATUS.CONTRACT_ONLY,
    requiredScopes: [AGENT_GRANT_SCOPES.READ],
    riskLevel: AGENT_RISK_LEVELS.HIGH,
    approvalBehavior: AGENT_EXECUTION_POLICIES.APPROVAL_REQUIRED,
    signingOrWorkerAuthority: 'managed_testnet_account_runtime_metadata_only',
    adaptersMayCallDirectly: adapters(false, false),
  },
  {
    actionId: AGENT_ACTION_IDS.ACCOUNT_LINK_REQUEST,
    family: 'account',
    route: route('POST', '/api/agent/accounts/link-request'),
    status: AGENT_ACTION_STATUS.CONTRACT_ONLY,
    requiredScopes: [AGENT_GRANT_SCOPES.READ],
    riskLevel: AGENT_RISK_LEVELS.MEDIUM,
    approvalBehavior: AGENT_EXECUTION_POLICIES.APPROVAL_REQUIRED,
    signingOrWorkerAuthority: 'none',
    adaptersMayCallDirectly: adapters(false, false),
  },
  {
    actionId: AGENT_ACTION_IDS.WORKER_SETUP_STATUS,
    family: 'worker_setup',
    route: route('GET', '/api/agent/worker-setup'),
    status: AGENT_ACTION_STATUS.CONTRACT_ONLY,
    requiredScopes: [AGENT_GRANT_SCOPES.READ],
    riskLevel: AGENT_RISK_LEVELS.READ,
    approvalBehavior: 'private_setup_status',
    signingOrWorkerAuthority: 'none',
    adaptersMayCallDirectly: adapters(false, false),
  },
  {
    actionId: AGENT_ACTION_IDS.WORKER_SETUP_ONBOARDING_CONFIG,
    family: 'worker_setup',
    route: route('POST', '/api/agent/worker-setup/onboarding'),
    status: AGENT_ACTION_STATUS.CONTRACT_ONLY,
    requiredScopes: [AGENT_GRANT_SCOPES.READ],
    riskLevel: AGENT_RISK_LEVELS.LOW,
    approvalBehavior: 'private_setup_config',
    signingOrWorkerAuthority: 'none',
    adaptersMayCallDirectly: adapters(false, false),
  },
  {
    actionId: AGENT_ACTION_IDS.QUESTION_GENERATION_REQUEST,
    family: 'question',
    route: route('POST', '/api/agent/questions/generate-request'),
    status: AGENT_ACTION_STATUS.DEFERRED,
    requiredScopes: [AGENT_GRANT_SCOPES.CREATE_QUESTION_REQUEST],
    riskLevel: AGENT_RISK_LEVELS.LOW,
    approvalBehavior: AGENT_EXECUTION_POLICIES.APPROVAL_REQUIRED,
    signingOrWorkerAuthority: 'none',
    adaptersMayCallDirectly: adapters(false, false),
  },
  {
    actionId: AGENT_ACTION_IDS.SURVEY_AUTHORING_REQUEST,
    family: 'survey',
    route: route('POST', '/api/agent/surveys/author-request'),
    status: AGENT_ACTION_STATUS.DEFERRED,
    requiredScopes: [AGENT_GRANT_SCOPES.CREATE_QUESTION_REQUEST],
    riskLevel: AGENT_RISK_LEVELS.MEDIUM,
    approvalBehavior: AGENT_EXECUTION_POLICIES.APPROVAL_REQUIRED,
    signingOrWorkerAuthority: 'may_require_ce_owned',
    adaptersMayCallDirectly: adapters(false, false),
  },
  {
    actionId: AGENT_ACTION_IDS.SBT_GROUP_DRAFT_REQUEST,
    family: 'sbt_group',
    route: route('POST', '/api/agent/sbt-groups/draft-request'),
    status: AGENT_ACTION_STATUS.DEFERRED,
    requiredScopes: [AGENT_GRANT_SCOPES.CREATE_QUESTION_REQUEST],
    riskLevel: AGENT_RISK_LEVELS.LOW,
    approvalBehavior: AGENT_EXECUTION_POLICIES.APPROVAL_REQUIRED,
    signingOrWorkerAuthority: 'none',
    adaptersMayCallDirectly: adapters(false, false),
  },
  {
    actionId: AGENT_ACTION_IDS.SBT_GROUP_CREATE_REQUEST,
    family: 'sbt_group',
    route: route('POST', '/api/agent/sbt-groups/create-request'),
    status: AGENT_ACTION_STATUS.DEFERRED,
    requiredScopes: [AGENT_GRANT_SCOPES.CREATE_QUESTION_REQUEST],
    riskLevel: AGENT_RISK_LEVELS.HIGH,
    approvalBehavior: AGENT_EXECUTION_POLICIES.APPROVAL_REQUIRED,
    signingOrWorkerAuthority: 'may_require_ce_owned',
    adaptersMayCallDirectly: adapters(false, false),
  },
  {
    actionId: AGENT_ACTION_IDS.SBT_GROUP_SHARE_REQUEST,
    family: 'sbt_group',
    route: route('POST', '/api/agent/sbt-groups/share-request'),
    status: AGENT_ACTION_STATUS.DEFERRED,
    requiredScopes: [AGENT_GRANT_SCOPES.CREATE_QUESTION_REQUEST],
    riskLevel: AGENT_RISK_LEVELS.MEDIUM,
    approvalBehavior: AGENT_EXECUTION_POLICIES.APPROVAL_REQUIRED,
    signingOrWorkerAuthority: 'none',
    adaptersMayCallDirectly: adapters(false, false),
  },
  {
    actionId: AGENT_ACTION_IDS.SBT_GROUP_CLAIM_REQUEST,
    family: 'sbt_group',
    route: route('POST', '/api/agent/sbt-groups/claim-request'),
    status: AGENT_ACTION_STATUS.DEFERRED,
    requiredScopes: [AGENT_GRANT_SCOPES.CREATE_QUESTION_REQUEST],
    riskLevel: AGENT_RISK_LEVELS.MEDIUM,
    approvalBehavior: AGENT_EXECUTION_POLICIES.APPROVAL_REQUIRED,
    signingOrWorkerAuthority: 'may_require_ce_owned',
    adaptersMayCallDirectly: adapters(false, false),
  },
  {
    actionId: AGENT_ACTION_IDS.SESSION_CREATE_REQUEST,
    family: 'session',
    route: route('POST', '/api/agent/sessions/create-request'),
    status: AGENT_ACTION_STATUS.DEFERRED,
    requiredScopes: [AGENT_GRANT_SCOPES.CREATE_QUESTION_REQUEST],
    riskLevel: AGENT_RISK_LEVELS.HIGH,
    approvalBehavior: AGENT_EXECUTION_POLICIES.APPROVAL_REQUIRED,
    signingOrWorkerAuthority: 'may_require_ce_owned',
    adaptersMayCallDirectly: adapters(false, false),
  },
  {
    actionId: AGENT_ACTION_IDS.SESSION_CONFIG_REQUEST,
    family: 'session',
    route: route('POST', '/api/agent/sessions/config-request'),
    status: AGENT_ACTION_STATUS.DEFERRED,
    requiredScopes: [AGENT_GRANT_SCOPES.CREATE_QUESTION_REQUEST],
    riskLevel: AGENT_RISK_LEVELS.MEDIUM,
    approvalBehavior: AGENT_EXECUTION_POLICIES.APPROVAL_REQUIRED,
    signingOrWorkerAuthority: 'may_require_ce_owned',
    adaptersMayCallDirectly: adapters(false, false),
  },
  {
    actionId: AGENT_ACTION_IDS.DELIBERATIVE_STATEMENT_SIGNAL_REQUEST,
    family: 'deliberation',
    route: route('POST', '/api/agent/deliberation/statements/signal-request'),
    status: AGENT_ACTION_STATUS.DEFERRED,
    requiredScopes: [AGENT_GRANT_SCOPES.SUBMIT_REQUEST],
    riskLevel: AGENT_RISK_LEVELS.MEDIUM,
    approvalBehavior: AGENT_EXECUTION_POLICIES.APPROVAL_REQUIRED,
    signingOrWorkerAuthority: 'may_require_ce_owned',
    adaptersMayCallDirectly: adapters(false, false),
  },
  {
    actionId: AGENT_ACTION_IDS.DELIBERATIVE_STATEMENT_PROPOSAL_REQUEST,
    family: 'deliberation',
    route: route('POST', '/api/agent/deliberation/statements/proposal-request'),
    status: AGENT_ACTION_STATUS.DEFERRED,
    requiredScopes: [AGENT_GRANT_SCOPES.CREATE_QUESTION_REQUEST],
    riskLevel: AGENT_RISK_LEVELS.MEDIUM,
    approvalBehavior: AGENT_EXECUTION_POLICIES.APPROVAL_REQUIRED,
    signingOrWorkerAuthority: 'may_require_ce_owned',
    adaptersMayCallDirectly: adapters(false, false),
  },
  {
    actionId: AGENT_ACTION_IDS.DELIBERATIVE_STATEMENT_RANKING_REQUEST,
    family: 'deliberation',
    route: route('POST', '/api/agent/deliberation/statements/ranking-request'),
    status: AGENT_ACTION_STATUS.DEFERRED,
    requiredScopes: [AGENT_GRANT_SCOPES.SUBMIT_REQUEST],
    riskLevel: AGENT_RISK_LEVELS.MEDIUM,
    approvalBehavior: AGENT_EXECUTION_POLICIES.APPROVAL_REQUIRED,
    signingOrWorkerAuthority: 'may_require_ce_owned',
    adaptersMayCallDirectly: adapters(false, false),
  },
];

export const AGENT_ACTION_INVENTORY = Object.freeze(
  ACTION_INVENTORY_ENTRIES.map((entry) => Object.freeze({
    ...entry,
    requiredScopes: Object.freeze(entry.requiredScopes.slice()),
  }))
);

export const AGENT_ACTION_INVENTORY_BY_ID = Object.freeze(
  Object.fromEntries(AGENT_ACTION_INVENTORY.map((entry) => [entry.actionId, entry]))
);

export function getAgentAction(actionId) {
  return AGENT_ACTION_INVENTORY_BY_ID[String(actionId || '').trim().toLowerCase()] || null;
}
