// ACCOUNT OPERATIONS
export const FETCH_ACCOUNT = 'FETCH_ACCOUNT';
export const LOGIN_ACCOUNT = 'LOGIN_ACCOUNT';
export const CHANGE_NETWORK = 'CHANGE_NETWORK';

// SITE-STATE OPERATIONS
export const CHANGE_METRICS_CHOICE = 'CHANGE_METRICS_CHOICE';
export const FETCH_SESSION_STATE = 'FETCH_SESSION_STATE';
export const TOGGLE_LOGIN_MODAL = 'TOGGLE_LOGIN_MODAL';
export const TOGGLE_TOOLTIPS = 'TOGGLE_TOOLTIPS';
export const SET_DEMO_SURFACE_MODE = 'SET_DEMO_SURFACE_MODE';
export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS';
export const CHANGE_FOCUSED_TAB = 'CHANGE_FOCUSED_TAB';
export const TOGGLE_DEMO_MODE = 'TOGGLE_DEMO_MODE';
export const CHANGE_ACTIVE_SESSION_SLUG = 'CHANGE_ACTIVE_SESSION_SLUG';
export const UPDATE_GLOBAL_SESSION_SELECTION = 'UPDATE_GLOBAL_SESSION_SELECTION';
export const SET_ONBOARDING_STEP = 'SET_ONBOARDING_STEP';
