export const resolveWorkerRouteRuntimeInput = ({
  deps,
  constants,
  defaults,
  workerLowLevelHelpers,
  anonymousUnknownIdentity = 'anon:unknown',
} = {}) => ({
  deps: {
    log: deps?.log,
    toStr: deps?.toStr,
    now: deps?.now,
    parseAllowOrigins: deps?.parseAllowOrigins,
    originAllowed: deps?.originAllowed,
    corsHeaders: deps?.corsHeaders,
    json: deps?.json,
    normalizeWorkerSessionSlug: deps?.normalizeWorkerSessionSlug,
    getSessionConfig: deps?.getSessionConfig,
    verifyToken: deps?.verifyToken,
    validateAuthTokenRecord: deps?.validateAuthTokenRecord,
    resolveWorkerRequestSlugContext: deps?.resolveWorkerRequestSlugContext,
    toChainId: deps?.toChainId,
    normalizeRpcUrlList: deps?.normalizeRpcUrlList,
    ...(workerLowLevelHelpers || {}),
    readTranscribeRequestPayload: deps?.readTranscribeRequestPayload,
    normalizeFaucetRequest: deps?.normalizeFaucetRequest,
    validateFaucetEligibilityRequest: deps?.validateFaucetEligibilityRequest,
    Wallet: deps?.ethers?.Wallet,
    normalizeFetchTargetUrl: deps?.normalizeFetchTargetUrl,
    readArweaveUploadRequestPayload: deps?.readArweaveUploadRequestPayload,
    resolveArweaveUploadJwk: deps?.resolveArweaveUploadJwk,
    normalizeArweaveCeTags: deps?.normalizeArweaveCeTags,
    normalizeArweaveAssociationTags: deps?.normalizeArweaveAssociationTags,
    normalizeSignedWorkerRequest: deps?.normalizeSignedWorkerRequest,
    resolveWorkerBodySlugContext: deps?.resolveWorkerBodySlugContext,
    validateRecoveredAddressMatchesRequest: deps?.validateRecoveredAddressMatchesRequest,
    parseSiweMessage: deps?.parseSiweMessage,
    validateSiwe: deps?.validateSiwe,
    validateTrustedLoginRequestOrigin: deps?.validateTrustedLoginRequestOrigin,
    validateBrowserLoginOrigin: deps?.validateBrowserLoginOrigin,
    resolveTrustedAdminOrigins: deps?.resolveTrustedAdminOrigins,
    validateSiweAddressMatchesRequest: deps?.validateSiweAddressMatchesRequest,
    consumeNonce: deps?.consumeNonce,
    buildNonce: deps?.buildNonce,
    checkNonceRateLimit: deps?.checkNonceRateLimit,
    base64UrlEncode: deps?.base64UrlEncode,
    signToken: deps?.signToken,
    buildAuthTokenJti: deps?.buildAuthTokenJti,
    persistAuthTokenRecord: deps?.persistAuthTokenRecord,
    readArweaveBootstrapUploadPayload: deps?.readArweaveBootstrapUploadPayload,
    getSessionSecrets: deps?.getSessionSecrets,
    mergeWorkerConfigRecords: deps?.mergeWorkerConfigRecords,
    mergeWorkerLimitRecords: deps?.mergeWorkerLimitRecords,
    putSessionConfig: deps?.putSessionConfig,
    normalizeSecretValue: deps?.normalizeSecretValue,
    putSessionSecrets: deps?.putSessionSecrets,
    dispatchAnonymousRoute: deps?.dispatchAnonymousRoute,
    storageRoute: deps?.storageRoute,
    readAiRequestPayload: deps?.readAiRequestPayload,
    validateAnonymousAiRequest: deps?.validateAnonymousAiRequest,
    dispatchAuthenticatedRoute: deps?.dispatchAuthenticatedRoute,
    dispatchAuthenticatedSecretPathRoute: deps?.dispatchAuthenticatedSecretPathRoute,
    readAuthenticatedActionPayload: deps?.readAuthenticatedActionPayload,
    dispatchAuthenticatedNonSecretActionRoute: deps?.dispatchAuthenticatedNonSecretActionRoute,
    dispatchAuthenticatedSecretActionRoute: deps?.dispatchAuthenticatedSecretActionRoute,
    evaluateAuthenticatedRoutePreflight: deps?.evaluateAuthenticatedRoutePreflight,
    resolveAuthenticatedRouteSecrets: deps?.resolveAuthenticatedRouteSecrets,
    normalizeAiRequestPayload: deps?.normalizeAiRequestPayload,
  },
  constants: {
    resourceGateKeys: constants?.RESOURCE_GATE_KEYS,
    anonymousRateIdHeader: constants?.ANONYMOUS_RATE_ID_HEADER,
    anonymousGateUnavailableError: constants?.ANONYMOUS_GATE_UNAVAILABLE_ERROR,
    missingSlugError: constants?.MISSING_SLUG_ERROR,
    anonymousRouteDeniedError: constants?.ANONYMOUS_ROUTE_DENIED_ERROR,
    anonymousScopeDisabledError: constants?.ANONYMOUS_SCOPE_DISABLED_ERROR,
    anonymousUnknownIdentity,
    openAiTranscribeUrl: constants?.OPENAI_TRANSCRIBE_URL,
    zeroBytes32: constants?.ZERO_BYTES32,
    slugAliasMismatchError: constants?.SLUG_ALIAS_MISMATCH_ERROR,
    slugMismatchError: constants?.SLUG_MISMATCH_ERROR,
    nonceTtlSeconds: constants?.NONCE_TTL_SECONDS,
    nonceRateLimitMax: constants?.NONCE_RATE_LIMIT_MAX,
    nonceRateLimitWindowMs: constants?.NONCE_RATE_LIMIT_WINDOW_MS,
    nonceRateLimitTtlSeconds: constants?.NONCE_RATE_LIMIT_TTL_SECONDS,
    usedNonceTtlSeconds: constants?.USED_NONCE_TTL_SECONDS,
    loginSiweMaxAgeMs: constants?.LOGIN_SIWE_MAX_AGE_MS,
    loginSiweFutureSkewMs: constants?.LOGIN_SIWE_FUTURE_SKEW_MS,
    tokenTtlSeconds: constants?.TOKEN_TTL_SECONDS,
    sessionConfigNotFoundError: constants?.SESSION_CONFIG_NOT_FOUND_ERROR,
    bootstrapSessionConfigRequiredError: constants?.BOOTSTRAP_SESSION_CONFIG_REQUIRED_ERROR,
  },
  defaults: {
    defaultRpcUrl: defaults?.DEFAULT_FAUCET_RPC_URL,
    defaultAmountEth: defaults?.DEFAULT_FAUCET_AMOUNT_ETH,
    defaultThresholdEth: defaults?.DEFAULT_FAUCET_BALANCE_THRESHOLD_ETH,
  },
});
