import test from 'node:test';
import assert from 'node:assert/strict';

import { createWorkerRouteRuntimeWithWorkerDeps } from './workerRouteRuntimeBinding.js';

test('createWorkerRouteRuntimeWithWorkerDeps returns the expected runtime contract', () => {
  const runtime = createWorkerRouteRuntimeWithWorkerDeps({
    deps: {
      createRegistryLoginBootstrapAdaptersWithWorkerDeps: () => ({
        computeScopesForLogin: 'computeScopesForLogin',
        readSessionExistsOnChain: 'readSessionExistsOnChain',
        readSessionBySlugOnChain: 'readSessionBySlugOnChain',
        validateBootstrapAdmin: 'validateBootstrapAdmin',
        readResourceGateOnChain: 'readResourceGateOnChain',
        readRegistryCodeOnChain: 'readRegistryCodeOnChain',
      }),
      createRateLimitFaucetSupportWithWorkerDeps: () => ({
        checkRateLimit: 'checkRateLimit',
        findSessionGateForSbt: 'findSessionGateForSbt',
        readSbtFaucetValidationState: 'readSbtFaucetValidationState',
        validateSbtPasswordForFaucet: 'validateSbtPasswordForFaucet',
      }),
      createAnonymousRegistrySupportAdaptersWithWorkerDeps: () => ({
        resolveRequestSlugWithoutToken: 'resolveRequestSlugWithoutToken',
        evaluateAnonymousRouteAccess: 'evaluateAnonymousRouteAccess',
        resolveAnonymousRateIdentity: 'resolveAnonymousRateIdentity',
      }),
      createAuthCorsAdminAdaptersWithWorkerDeps: () => ({
        getCorsContext: 'getCorsContext',
        resolveExistingSessionCors: 'resolveExistingSessionCors',
        requireAuth: 'requireAuth',
        validateAdmin: 'validateAdmin',
      }),
      createWorkerExecutionServicesWithWorkerDeps: () => ({
        proxyAnthropic: 'proxyAnthropic',
        proxyOpenAI: 'proxyOpenAI',
        proxyOpenRouter: 'proxyOpenRouter',
        proxyCustomRPC: 'proxyCustomRPC',
        transcribe: 'transcribe',
        faucet: 'faucet',
        fetchImage: 'fetchImage',
        fetchUrl: 'fetchUrl',
        arweaveUpload: 'arweaveUpload',
        storageRoute: 'storageRoute',
        verifyAdminSignature: 'verifyAdminSignature',
      }),
      createWorkerRouteShellWithWorkerDeps: () => ({
        fetch: 'fetch',
      }),
    },
  });

  assert.deepEqual(runtime.workerAuthGateUtils, {
    computeScopesForLogin: 'computeScopesForLogin',
    evaluateAnonymousRouteAccess: 'evaluateAnonymousRouteAccess',
    resolveAnonymousRateIdentity: 'resolveAnonymousRateIdentity',
  });
  assert.equal(runtime.fetch, 'fetch');
});

test('createWorkerRouteRuntimeWithWorkerDeps preserves route runtime assembly bundles', () => {
  const calls = [];
  const log = () => {};
  const now = () => 1234567890;

  const runtime = createWorkerRouteRuntimeWithWorkerDeps({
    deps: {
      createRegistryLoginBootstrapAdaptersWithWorkerDeps: (value) => {
        calls.push('registry');
        assert.deepEqual(value, {
          deps: {
            callRegistryFunction: 'callRegistryFunction',
            rpcRequest: 'rpcRequest',
            maskRpcUrl: 'maskRpcUrl',
            toStr: 'toStr',
            isAddress: 'isAddress',
            toChainId: 'toChainId',
            normalizeRpcUrlList: 'normalizeRpcUrlList',
            resolveRegistryRpcUrls: 'resolveRegistryRpcUrls',
            resolveRpcUrlListForGate: 'resolveRpcUrlListForGate',
            toRegistrySessionSlug: 'toRegistrySessionSlug',
            checkSbtGate: 'checkSbtGate',
            probeRpcUrls: 'probeRpcUrls',
          },
          constants: {
            resourceGateKeys: ['default', 'ai', 'arweave'],
          },
        });
        return {
          computeScopesForLogin: 'computeScopesForLogin',
          readSessionExistsOnChain: 'readSessionExistsOnChain',
          readSessionBySlugOnChain: 'readSessionBySlugOnChain',
          validateBootstrapAdmin: 'validateBootstrapAdmin',
          readResourceGateOnChain: 'readResourceGateOnChain',
          readRegistryCodeOnChain: 'readRegistryCodeOnChain',
        };
      },
      createRateLimitFaucetSupportWithWorkerDeps: (value) => {
        calls.push('rateLimit');
        assert.deepEqual(value, {
          deps: {
            toStr: 'toStr',
            now,
            isAddress: 'isAddress',
            resolveRegistryRpcUrls: 'resolveRegistryRpcUrls',
            normalizeAddressLower: 'normalizeAddressLower',
            toRegistrySessionSlug: 'toRegistrySessionSlug',
            readSessionExistsOnChain: 'readSessionExistsOnChain',
            maskRpcUrl: 'maskRpcUrl',
            readResourceGateOnChain: 'readResourceGateOnChain',
            resolveRpcUrlListForGate: 'resolveRpcUrlListForGate',
            toChainId: 'toChainId',
            rpcRequest: 'rpcRequest',
            getFaucetSbtGateInterface: 'getFaucetSbtGateInterface',
            callContractFunction: 'callContractFunction',
          },
          constants: {
            anonymousGateUnavailableError: 'anonymousGateUnavailableError',
            resourceGateKeys: ['default', 'ai', 'arweave'],
            zeroBytes32: 'zeroBytes32',
          },
        });
        return {
          checkRateLimit: 'checkRateLimit',
          findSessionGateForSbt: 'findSessionGateForSbt',
          readSbtFaucetValidationState: 'readSbtFaucetValidationState',
          validateSbtPasswordForFaucet: 'validateSbtPasswordForFaucet',
        };
      },
      createAnonymousRegistrySupportAdaptersWithWorkerDeps: (value) => {
        calls.push('anonymous');
        assert.deepEqual(value, {
          deps: {
            resolveWorkerRequestSlugContext: 'resolveWorkerRequestSlugContext',
            toStr: 'toStr',
            isAddress: 'isAddress',
            resolveRegistryRpcUrls: 'resolveRegistryRpcUrls',
            toRegistrySessionSlug: 'toRegistrySessionSlug',
            maskRpcUrl: 'maskRpcUrl',
            readSessionExistsOnChain: 'readSessionExistsOnChain',
            readResourceGateOnChain: 'readResourceGateOnChain',
          },
          constants: {
            anonymousGateUnavailableError: 'anonymousGateUnavailableError',
            anonymousRouteDeniedError: 'anonymousRouteDeniedError',
            anonymousScopeDisabledError: 'anonymousScopeDisabledError',
            anonymousRateIdHeader: 'X-Anonymous-Client-Id',
            anonymousUnknownIdentity: 'anon:unknown',
          },
        });
        return {
          resolveRequestSlugWithoutToken: 'resolveRequestSlugWithoutToken',
          evaluateAnonymousRouteAccess: 'evaluateAnonymousRouteAccess',
          resolveAnonymousRateIdentity: 'resolveAnonymousRateIdentity',
        };
      },
      createAuthCorsAdminAdaptersWithWorkerDeps: (value) => {
        calls.push('authCorsAdmin');
        assert.deepEqual(value, {
          deps: {
            parseAllowOrigins: 'parseAllowOrigins',
            originAllowed: 'originAllowed',
            corsHeaders: 'corsHeaders',
            json: 'json',
            normalizeWorkerSessionSlug: 'normalizeWorkerSessionSlug',
            getSessionConfig: 'getSessionConfig',
            resolveTrustedAdminOrigins: 'resolveTrustedAdminOrigins',
            verifyToken: 'verifyToken',
            validateAuthTokenRecord: 'validateAuthTokenRecord',
            resolveWorkerRequestSlugContext: 'resolveWorkerRequestSlugContext',
            toStr: 'toStr',
            isAddress: 'isAddress',
            resolveRegistryRpcUrls: 'resolveRegistryRpcUrls',
            rpcRequest: 'rpcRequest',
            toChainId: 'toChainId',
            getHatsInterface: 'getHatsInterface',
            callContractFunction: 'callContractFunction',
          },
          constants: {
            missingSlugError: 'missingSlugError',
          },
        });
        return {
          getCorsContext: 'getCorsContext',
          resolveExistingSessionCors: 'resolveExistingSessionCors',
          requireAuth: 'requireAuth',
          validateAdmin: 'validateAdmin',
        };
      },
      createWorkerExecutionServicesWithWorkerDeps: (value) => {
        calls.push('execution');
        assert.deepEqual(value.deps, {
          fetch: 'fetch',
          json: 'json',
          safeFetch: 'safeFetch',
          isBlockedOutboundUrl: 'isBlockedOutboundUrl',
          toStr: 'toStr',
          Wallet: 'Wallet',
          rpcRequest: 'rpcRequest',
          toChainId: 'toChainId',
          toBigInt: 'toBigInt',
          formatEther: 'formatEther',
          maskRpcUrl: 'maskRpcUrl',
          isAddress: 'isAddress',
          parseEther: 'parseEther',
          resolveFaucetRpcUrls: 'resolveFaucetRpcUrls',
          isBytes32Hex: 'isBytes32Hex',
          normalizeAddressLower: 'normalizeAddressLower',
          resolveRegistryRpcUrls: 'resolveRegistryRpcUrls',
          toRegistrySessionSlug: 'toRegistrySessionSlug',
          readSessionExistsOnChain: 'readSessionExistsOnChain',
          readResourceGateOnChain: 'readResourceGateOnChain',
          resolveRpcUrlListForGate: 'resolveRpcUrlListForGate',
          checkSbtGate: 'checkSbtGate',
          findSessionGateForSbt: 'findSessionGateForSbt',
          readSbtFaucetValidationState: 'readSbtFaucetValidationState',
          validateSbtPasswordForFaucet: 'validateSbtPasswordForFaucet',
          verifyGroupSignatureForFaucet: 'verifyGroupSignatureForFaucet',
          callContractFunction: 'callContractFunction',
          readSessionBySlugOnChain: 'readSessionBySlugOnChain',
          getErc721Interface: 'getErc721Interface',
          getSbtAdminInterface: 'getSbtAdminInterface',
          isPositiveBalance: 'isPositiveBalance',
          normalizeSessionIdHex: 'normalizeSessionIdHex',
          normalizeSignedWorkerRequest: 'normalizeSignedWorkerRequest',
          resolveWorkerBodySlugContext: 'resolveWorkerBodySlugContext',
          verifyMessage: 'verifyMessage',
          validateRecoveredAddressMatchesRequest: 'validateRecoveredAddressMatchesRequest',
          parseSiweMessage: 'parseSiweMessage',
          validateSiwe: 'validateSiwe',
          validateTrustedLoginRequestOrigin: 'validateTrustedLoginRequestOrigin',
          validateBrowserLoginOrigin: 'validateBrowserLoginOrigin',
          validateSiweAddressMatchesRequest: 'validateSiweAddressMatchesRequest',
          consumeNonce: 'consumeNonce',
          validateAdmin: 'validateAdmin',
          log,
          now,
          randomUUID: 'randomUUID',
          getSessionSecrets: 'getSessionSecrets',
          putSessionConfig: 'putSessionConfig',
        });
        assert.deepEqual(value.constants, {
          openAiTranscribeUrl: 'https://api.openai.example/v1/audio/transcriptions',
          anonymousGateUnavailableError: 'anonymousGateUnavailableError',
          zeroBytes32: 'zeroBytes32',
          usedNonceTtlSeconds: 600,
          missingSlugError: 'missingSlugError',
          slugAliasMismatchError: 'slugAliasMismatchError',
          slugMismatchError: 'slugMismatchError',
        });
        assert.deepEqual(value.defaults, {
          defaultRpcUrl: 'defaultRpcUrl',
          defaultAmountEth: 'defaultAmountEth',
          defaultThresholdEth: 'defaultThresholdEth',
        });
        return {
          proxyAnthropic: 'proxyAnthropic',
          proxyOpenAI: 'proxyOpenAI',
          proxyOpenRouter: 'proxyOpenRouter',
          proxyCustomRPC: 'proxyCustomRPC',
          transcribe: 'transcribe',
          faucet: 'faucet',
          fetchImage: 'fetchImage',
          fetchUrl: 'fetchUrl',
          arweaveUpload: 'arweaveUpload',
          storageRoute: 'storageRoute',
          verifyAdminSignature: 'verifyAdminSignature',
        };
      },
      createWorkerRouteShellWithWorkerDeps: (value) => {
        calls.push('routeShell');
        assert.deepEqual(value.deps, {
          log,
          fetch: 'fetch',
          toStr: 'toStr',
          corsHeaders: 'corsHeaders',
          json: 'json',
          isAddress: 'isAddress',
          resolveWorkerBodySlugContext: 'resolveWorkerBodySlugContext',
          resolveExistingSessionCors: 'resolveExistingSessionCors',
          resolveTrustedAdminOrigins: 'resolveTrustedAdminOrigins',
          validateTrustedLoginRequestOrigin: 'validateTrustedLoginRequestOrigin',
          buildNonce: 'buildNonce',
          checkNonceRateLimit: 'checkNonceRateLimit',
          base64UrlEncode: 'base64UrlEncode',
          normalizeSignedWorkerRequest: 'normalizeSignedWorkerRequest',
          verifyMessage: 'verifyMessage',
          validateRecoveredAddressMatchesRequest: 'validateRecoveredAddressMatchesRequest',
          parseSiweMessage: 'parseSiweMessage',
          validateSiwe: 'validateSiwe',
          validateBrowserLoginOrigin: 'validateBrowserLoginOrigin',
          validateSiweAddressMatchesRequest: 'validateSiweAddressMatchesRequest',
          consumeNonce: 'consumeNonce',
          computeScopesForLogin: 'computeScopesForLogin',
          signToken: 'signToken',
          getAddress: 'getAddress',
          buildAuthTokenJti: 'buildAuthTokenJti',
          persistAuthTokenRecord: 'persistAuthTokenRecord',
          now,
          readArweaveBootstrapUploadPayload: 'readArweaveBootstrapUploadPayload',
          getSessionConfig: 'getSessionConfig',
          getCorsContext: 'getCorsContext',
          verifyAdminSignature: 'verifyAdminSignature',
          getSessionSecrets: 'getSessionSecrets',
          arweaveUpload: 'arweaveUpload',
          storageRoute: 'storageRoute',
          validateBootstrapAdmin: 'validateBootstrapAdmin',
          validateAdmin: 'validateAdmin',
          mergeWorkerConfigRecords: 'mergeWorkerConfigRecords',
          mergeWorkerLimitRecords: 'mergeWorkerLimitRecords',
          putSessionConfig: 'putSessionConfig',
          normalizeSecretValue: 'normalizeSecretValue',
          putSessionSecrets: 'putSessionSecrets',
          resolveRequestSlugWithoutToken: 'resolveRequestSlugWithoutToken',
          resolveAnonymousRateIdentity: 'resolveAnonymousRateIdentity',
          checkRateLimit: 'checkRateLimit',
          dispatchAnonymousRoute: 'dispatchAnonymousRoute',
          readTranscribeRequestPayload: 'readTranscribeRequestPayload',
          evaluateAnonymousRouteAccess: 'evaluateAnonymousRouteAccess',
          transcribe: 'transcribe',
          readAiRequestPayload: 'readAiRequestPayload',
          validateAnonymousAiRequest: 'validateAnonymousAiRequest',
          proxyAnthropic: 'proxyAnthropic',
          proxyOpenAI: 'proxyOpenAI',
          proxyOpenRouter: 'proxyOpenRouter',
          proxyCustomRPC: 'proxyCustomRPC',
          requireAuth: 'requireAuth',
          dispatchAuthenticatedRoute: 'dispatchAuthenticatedRoute',
          dispatchAuthenticatedSecretPathRoute: 'dispatchAuthenticatedSecretPathRoute',
          readAuthenticatedActionPayload: 'readAuthenticatedActionPayload',
          dispatchAuthenticatedNonSecretActionRoute: 'dispatchAuthenticatedNonSecretActionRoute',
          dispatchAuthenticatedSecretActionRoute: 'dispatchAuthenticatedSecretActionRoute',
          evaluateAuthenticatedRoutePreflight: 'evaluateAuthenticatedRoutePreflight',
          resolveAuthenticatedRouteSecrets: 'resolveAuthenticatedRouteSecrets',
          fetchImage: 'fetchImage',
          fetchUrl: 'fetchUrl',
          normalizeAiRequestPayload: 'normalizeAiRequestPayload',
          faucet: 'faucet',
        });
        assert.deepEqual(value.constants, {
          missingSlugError: 'missingSlugError',
          nonceTtlSeconds: 300,
          nonceRateLimitMax: 5,
          nonceRateLimitWindowMs: 60000,
          nonceRateLimitTtlSeconds: 60,
          usedNonceTtlSeconds: 600,
          tokenTtlSeconds: 86400,
          loginSiweMaxAgeMs: 300000,
          loginSiweFutureSkewMs: 60000,
          sessionConfigNotFoundError: 'sessionConfigNotFoundError',
          bootstrapSessionConfigRequiredError: 'bootstrapSessionConfigRequiredError',
          anonymousRouteDeniedError: 'anonymousRouteDeniedError',
        });
        return {
          fetch: 'fetch',
        };
      },
      callRegistryFunction: 'callRegistryFunction',
      rpcRequest: 'rpcRequest',
      maskRpcUrl: 'maskRpcUrl',
      toStr: 'toStr',
      isAddress: 'isAddress',
      toChainId: 'toChainId',
      normalizeRpcUrlList: 'normalizeRpcUrlList',
      resolveRegistryRpcUrls: 'resolveRegistryRpcUrls',
      resolveRpcUrlListForGate: 'resolveRpcUrlListForGate',
      toRegistrySessionSlug: 'toRegistrySessionSlug',
      checkSbtGate: 'checkSbtGate',
      probeRpcUrls: 'probeRpcUrls',
      normalizeAddressLower: 'normalizeAddressLower',
      getFaucetSbtGateInterface: 'getFaucetSbtGateInterface',
      resolveWorkerRequestSlugContext: 'resolveWorkerRequestSlugContext',
      parseAllowOrigins: 'parseAllowOrigins',
      originAllowed: 'originAllowed',
      corsHeaders: 'corsHeaders',
      json: 'json',
      normalizeWorkerSessionSlug: 'normalizeWorkerSessionSlug',
      getSessionConfig: 'getSessionConfig',
      resolveTrustedAdminOrigins: 'resolveTrustedAdminOrigins',
      verifyToken: 'verifyToken',
      validateAuthTokenRecord: 'validateAuthTokenRecord',
      getHatsInterface: 'getHatsInterface',
      callContractFunction: 'callContractFunction',
      fetch: 'fetch',
      safeFetch: 'safeFetch',
      isBlockedOutboundUrl: 'isBlockedOutboundUrl',
      readTranscribeRequestPayload: 'readTranscribeRequestPayload',
      Wallet: 'Wallet',
      toBigInt: 'toBigInt',
      formatEther: 'formatEther',
      parseEther: 'parseEther',
      resolveFaucetRpcUrls: 'resolveFaucetRpcUrls',
      isBytes32Hex: 'isBytes32Hex',
      readSessionExistsOnChain: 'readSessionExistsOnChain',
      readResourceGateOnChain: 'readResourceGateOnChain',
      verifyGroupSignatureForFaucet: 'verifyGroupSignatureForFaucet',
      getErc721Interface: 'getErc721Interface',
      getSbtAdminInterface: 'getSbtAdminInterface',
      isPositiveBalance: 'isPositiveBalance',
      normalizeSessionIdHex: 'normalizeSessionIdHex',
      normalizeSignedWorkerRequest: 'normalizeSignedWorkerRequest',
      resolveWorkerBodySlugContext: 'resolveWorkerBodySlugContext',
      verifyMessage: 'verifyMessage',
      validateRecoveredAddressMatchesRequest: 'validateRecoveredAddressMatchesRequest',
      parseSiweMessage: 'parseSiweMessage',
      validateSiwe: 'validateSiwe',
      validateTrustedLoginRequestOrigin: 'validateTrustedLoginRequestOrigin',
      validateBrowserLoginOrigin: 'validateBrowserLoginOrigin',
      validateSiweAddressMatchesRequest: 'validateSiweAddressMatchesRequest',
      consumeNonce: 'consumeNonce',
      checkNonceRateLimit: 'checkNonceRateLimit',
      buildNonce: 'buildNonce',
      base64UrlEncode: 'base64UrlEncode',
      signToken: 'signToken',
      getAddress: 'getAddress',
      buildAuthTokenJti: 'buildAuthTokenJti',
      persistAuthTokenRecord: 'persistAuthTokenRecord',
      now,
      readArweaveBootstrapUploadPayload: 'readArweaveBootstrapUploadPayload',
      getSessionSecrets: 'getSessionSecrets',
      randomUUID: 'randomUUID',
      mergeWorkerConfigRecords: 'mergeWorkerConfigRecords',
      mergeWorkerLimitRecords: 'mergeWorkerLimitRecords',
      putSessionConfig: 'putSessionConfig',
      normalizeSecretValue: 'normalizeSecretValue',
      putSessionSecrets: 'putSessionSecrets',
      dispatchAnonymousRoute: 'dispatchAnonymousRoute',
      storageRoute: 'storageRoute',
      readAiRequestPayload: 'readAiRequestPayload',
      validateAnonymousAiRequest: 'validateAnonymousAiRequest',
      dispatchAuthenticatedRoute: 'dispatchAuthenticatedRoute',
      dispatchAuthenticatedSecretPathRoute: 'dispatchAuthenticatedSecretPathRoute',
      readAuthenticatedActionPayload: 'readAuthenticatedActionPayload',
      dispatchAuthenticatedNonSecretActionRoute: 'dispatchAuthenticatedNonSecretActionRoute',
      dispatchAuthenticatedSecretActionRoute: 'dispatchAuthenticatedSecretActionRoute',
      evaluateAuthenticatedRoutePreflight: 'evaluateAuthenticatedRoutePreflight',
      resolveAuthenticatedRouteSecrets: 'resolveAuthenticatedRouteSecrets',
      normalizeAiRequestPayload: 'normalizeAiRequestPayload',
      log,
    },
    constants: {
      resourceGateKeys: ['default', 'ai', 'arweave'],
      anonymousRateIdHeader: 'X-Anonymous-Client-Id',
      anonymousGateUnavailableError: 'anonymousGateUnavailableError',
      missingSlugError: 'missingSlugError',
      anonymousRouteDeniedError: 'anonymousRouteDeniedError',
      anonymousScopeDisabledError: 'anonymousScopeDisabledError',
      anonymousUnknownIdentity: 'anon:unknown',
      openAiTranscribeUrl: 'https://api.openai.example/v1/audio/transcriptions',
      zeroBytes32: 'zeroBytes32',
      slugAliasMismatchError: 'slugAliasMismatchError',
      slugMismatchError: 'slugMismatchError',
      nonceTtlSeconds: 300,
      nonceRateLimitMax: 5,
      nonceRateLimitWindowMs: 60000,
      nonceRateLimitTtlSeconds: 60,
      usedNonceTtlSeconds: 600,
      tokenTtlSeconds: 86400,
      loginSiweMaxAgeMs: 300000,
      loginSiweFutureSkewMs: 60000,
      sessionConfigNotFoundError: 'sessionConfigNotFoundError',
      bootstrapSessionConfigRequiredError: 'bootstrapSessionConfigRequiredError',
    },
    defaults: {
      defaultRpcUrl: 'defaultRpcUrl',
      defaultAmountEth: 'defaultAmountEth',
      defaultThresholdEth: 'defaultThresholdEth',
    },
  });

  assert.deepEqual(runtime.workerAuthGateUtils, {
    computeScopesForLogin: 'computeScopesForLogin',
    evaluateAnonymousRouteAccess: 'evaluateAnonymousRouteAccess',
    resolveAnonymousRateIdentity: 'resolveAnonymousRateIdentity',
  });
  assert.equal(runtime.fetch, 'fetch');
  assert.deepEqual(calls, [
    'registry',
    'rateLimit',
    'anonymous',
    'authCorsAdmin',
    'execution',
    'routeShell',
  ]);
});
