import test from 'node:test';
import assert from 'node:assert/strict';

import {
  resolveWorkerRouteRuntimeInput,
} from './workerRouteRuntimeInputResolution.js';

test('resolveWorkerRouteRuntimeInput preserves route-runtime deps/constants/defaults assembly', () => {
  const walletCtor = function Wallet() {};
  const workerLowLevelHelpers = {
    isBlockedOutboundUrl: 'isBlockedOutboundUrl',
    safeFetch: 'safeFetch',
    normalizeSessionIdHex: 'normalizeSessionIdHex',
    toBigInt: 'toBigInt',
    isAddress: 'isAddress',
    getAddress: 'getAddress',
    verifyMessage: 'verifyMessage',
    getBytes: 'getBytes',
    solidityKeccak256: 'solidityKeccak256',
    parseEther: 'parseEther',
    formatEther: 'formatEther',
    toRegistrySessionSlug: 'toRegistrySessionSlug',
    resolveRegistryRpcUrls: 'resolveRegistryRpcUrls',
    resolveRegistryRpcUrl: 'resolveRegistryRpcUrl',
    resolveRpcUrlListForGate: 'resolveRpcUrlListForGate',
    resolveFaucetRpcUrls: 'resolveFaucetRpcUrls',
    isBytes32Hex: 'isBytes32Hex',
    getRegistryInterface: 'getRegistryInterface',
    getErc721Interface: 'getErc721Interface',
    getSbtAdminInterface: 'getSbtAdminInterface',
    getHatsInterface: 'getHatsInterface',
    getFaucetSbtGateInterface: 'getFaucetSbtGateInterface',
    isPositiveBalance: 'isPositiveBalance',
    checkSbtGate: 'checkSbtGate',
    normalizeAddressLower: 'normalizeAddressLower',
    verifyGroupSignatureForFaucet: 'verifyGroupSignatureForFaucet',
    maskRpcUrl: 'maskRpcUrl',
    rpcRequest: 'rpcRequest',
    callContractFunction: 'callContractFunction',
    callRegistryFunction: 'callRegistryFunction',
    probeRpcUrls: 'probeRpcUrls',
  };

  const result = resolveWorkerRouteRuntimeInput({
    deps: {
      log: 'log',
      toStr: 'toStr',
      now: 'now',
      parseAllowOrigins: 'parseAllowOrigins',
      originAllowed: 'originAllowed',
      corsHeaders: 'corsHeaders',
      json: 'json',
      normalizeWorkerSessionSlug: 'normalizeWorkerSessionSlug',
      getSessionConfig: 'getSessionConfig',
      verifyToken: 'verifyToken',
      validateAuthTokenRecord: 'validateAuthTokenRecord',
      resolveWorkerRequestSlugContext: 'resolveWorkerRequestSlugContext',
      toChainId: 'toChainId',
      normalizeRpcUrlList: 'normalizeRpcUrlList',
      readTranscribeRequestPayload: 'readTranscribeRequestPayload',
      normalizeFaucetRequest: 'normalizeFaucetRequest',
      validateFaucetEligibilityRequest: 'validateFaucetEligibilityRequest',
      ethers: { Wallet: walletCtor },
      normalizeFetchTargetUrl: 'normalizeFetchTargetUrl',
      readArweaveUploadRequestPayload: 'readArweaveUploadRequestPayload',
      resolveArweaveUploadJwk: 'resolveArweaveUploadJwk',
      normalizeArweaveCeTags: 'normalizeArweaveCeTags',
      normalizeArweaveAssociationTags: 'normalizeArweaveAssociationTags',
      normalizeSignedWorkerRequest: 'normalizeSignedWorkerRequest',
      resolveWorkerBodySlugContext: 'resolveWorkerBodySlugContext',
      validateRecoveredAddressMatchesRequest: 'validateRecoveredAddressMatchesRequest',
      parseSiweMessage: 'parseSiweMessage',
      validateSiwe: 'validateSiwe',
      validateTrustedLoginRequestOrigin: 'validateTrustedLoginRequestOrigin',
      validateBrowserLoginOrigin: 'validateBrowserLoginOrigin',
      resolveTrustedAdminOrigins: 'resolveTrustedAdminOrigins',
      validateSiweAddressMatchesRequest: 'validateSiweAddressMatchesRequest',
      consumeNonce: 'consumeNonce',
      buildNonce: 'buildNonce',
      checkNonceRateLimit: 'checkNonceRateLimit',
      base64UrlEncode: 'base64UrlEncode',
      signToken: 'signToken',
      buildAuthTokenJti: 'buildAuthTokenJti',
      persistAuthTokenRecord: 'persistAuthTokenRecord',
      readArweaveBootstrapUploadPayload: 'readArweaveBootstrapUploadPayload',
      getSessionSecrets: 'getSessionSecrets',
      mergeWorkerConfigRecords: 'mergeWorkerConfigRecords',
      mergeWorkerLimitRecords: 'mergeWorkerLimitRecords',
      putSessionConfig: 'putSessionConfig',
      normalizeSecretValue: 'normalizeSecretValue',
      putSessionSecrets: 'putSessionSecrets',
      dispatchAnonymousRoute: 'dispatchAnonymousRoute',
      storageRoute: 'storageRoute',
      readAiRequestPayload: 'readAiRequestPayload',
      validateAnonymousAiRequest: 'validateAnonymousAiRequest',
      dispatchAuthenticatedRoute: 'dispatchAuthenticatedRoute',
      dispatchAuthenticatedSecretPathRoute: 'dispatchAuthenticatedSecretPathRoute',
      readAuthenticatedActionPayload: 'readAuthenticatedActionPayload',
      dispatchAuthenticatedNonSecretActionRoute: 'dispatchAuthenticatedNonSecretActionRoute',
      dispatchAuthenticatedSecretActionRoute: 'dispatchAuthenticatedSecretActionRoute',
      evaluateAuthenticatedRoutePreflight: 'evaluateAuthenticatedRoutePreflight',
      resolveAuthenticatedRouteSecrets: 'resolveAuthenticatedRouteSecrets',
      normalizeAiRequestPayload: 'normalizeAiRequestPayload',
    },
    constants: {
      RESOURCE_GATE_KEYS: ['default', 'ai', 'arweave'],
      ANONYMOUS_RATE_ID_HEADER: 'X-Anonymous-Client-Id',
      ANONYMOUS_GATE_UNAVAILABLE_ERROR: 'anonymousGateUnavailableError',
      MISSING_SLUG_ERROR: 'missingSlugError',
      ANONYMOUS_ROUTE_DENIED_ERROR: 'anonymousRouteDeniedError',
      ANONYMOUS_SCOPE_DISABLED_ERROR: 'anonymousScopeDisabledError',
      OPENAI_TRANSCRIBE_URL: 'https://api.openai.example/v1/audio/transcriptions',
      ZERO_BYTES32: 'zeroBytes32',
      SLUG_ALIAS_MISMATCH_ERROR: 'slugAliasMismatchError',
      SLUG_MISMATCH_ERROR: 'slugMismatchError',
      NONCE_TTL_SECONDS: 300,
      NONCE_RATE_LIMIT_MAX: 5,
      NONCE_RATE_LIMIT_WINDOW_MS: 60000,
      NONCE_RATE_LIMIT_TTL_SECONDS: 60,
      USED_NONCE_TTL_SECONDS: 600,
      LOGIN_SIWE_MAX_AGE_MS: 300000,
      LOGIN_SIWE_FUTURE_SKEW_MS: 60000,
      TOKEN_TTL_SECONDS: 86400,
      SESSION_CONFIG_NOT_FOUND_ERROR: 'sessionConfigNotFoundError',
      BOOTSTRAP_SESSION_CONFIG_REQUIRED_ERROR: 'bootstrapSessionConfigRequiredError',
    },
    defaults: {
      DEFAULT_FAUCET_RPC_URL: 'defaultFaucetRpcUrl',
      DEFAULT_FAUCET_AMOUNT_ETH: 'defaultAmountEth',
      DEFAULT_FAUCET_BALANCE_THRESHOLD_ETH: 'defaultThresholdEth',
    },
    workerLowLevelHelpers,
    anonymousUnknownIdentity: 'anon:unknown',
  });

  assert.deepEqual(result.deps, {
    log: 'log',
    toStr: 'toStr',
    now: 'now',
    parseAllowOrigins: 'parseAllowOrigins',
    originAllowed: 'originAllowed',
    corsHeaders: 'corsHeaders',
    json: 'json',
    normalizeWorkerSessionSlug: 'normalizeWorkerSessionSlug',
    getSessionConfig: 'getSessionConfig',
    verifyToken: 'verifyToken',
    validateAuthTokenRecord: 'validateAuthTokenRecord',
    resolveWorkerRequestSlugContext: 'resolveWorkerRequestSlugContext',
    toChainId: 'toChainId',
    normalizeRpcUrlList: 'normalizeRpcUrlList',
    ...workerLowLevelHelpers,
    readTranscribeRequestPayload: 'readTranscribeRequestPayload',
    normalizeFaucetRequest: 'normalizeFaucetRequest',
    validateFaucetEligibilityRequest: 'validateFaucetEligibilityRequest',
    Wallet: walletCtor,
    normalizeFetchTargetUrl: 'normalizeFetchTargetUrl',
    readArweaveUploadRequestPayload: 'readArweaveUploadRequestPayload',
    resolveArweaveUploadJwk: 'resolveArweaveUploadJwk',
    normalizeArweaveCeTags: 'normalizeArweaveCeTags',
    normalizeArweaveAssociationTags: 'normalizeArweaveAssociationTags',
    normalizeSignedWorkerRequest: 'normalizeSignedWorkerRequest',
    resolveWorkerBodySlugContext: 'resolveWorkerBodySlugContext',
    validateRecoveredAddressMatchesRequest: 'validateRecoveredAddressMatchesRequest',
    parseSiweMessage: 'parseSiweMessage',
    validateSiwe: 'validateSiwe',
    validateTrustedLoginRequestOrigin: 'validateTrustedLoginRequestOrigin',
    validateBrowserLoginOrigin: 'validateBrowserLoginOrigin',
    resolveTrustedAdminOrigins: 'resolveTrustedAdminOrigins',
    validateSiweAddressMatchesRequest: 'validateSiweAddressMatchesRequest',
    consumeNonce: 'consumeNonce',
    buildNonce: 'buildNonce',
    checkNonceRateLimit: 'checkNonceRateLimit',
    base64UrlEncode: 'base64UrlEncode',
    signToken: 'signToken',
    buildAuthTokenJti: 'buildAuthTokenJti',
    persistAuthTokenRecord: 'persistAuthTokenRecord',
    readArweaveBootstrapUploadPayload: 'readArweaveBootstrapUploadPayload',
    getSessionSecrets: 'getSessionSecrets',
    mergeWorkerConfigRecords: 'mergeWorkerConfigRecords',
    mergeWorkerLimitRecords: 'mergeWorkerLimitRecords',
    putSessionConfig: 'putSessionConfig',
    normalizeSecretValue: 'normalizeSecretValue',
    putSessionSecrets: 'putSessionSecrets',
    dispatchAnonymousRoute: 'dispatchAnonymousRoute',
    storageRoute: 'storageRoute',
    readAiRequestPayload: 'readAiRequestPayload',
    validateAnonymousAiRequest: 'validateAnonymousAiRequest',
    dispatchAuthenticatedRoute: 'dispatchAuthenticatedRoute',
    dispatchAuthenticatedSecretPathRoute: 'dispatchAuthenticatedSecretPathRoute',
    readAuthenticatedActionPayload: 'readAuthenticatedActionPayload',
    dispatchAuthenticatedNonSecretActionRoute: 'dispatchAuthenticatedNonSecretActionRoute',
    dispatchAuthenticatedSecretActionRoute: 'dispatchAuthenticatedSecretActionRoute',
    evaluateAuthenticatedRoutePreflight: 'evaluateAuthenticatedRoutePreflight',
    resolveAuthenticatedRouteSecrets: 'resolveAuthenticatedRouteSecrets',
    normalizeAiRequestPayload: 'normalizeAiRequestPayload',
  });
  assert.deepEqual(result.constants, {
    resourceGateKeys: ['default', 'ai', 'arweave'],
    anonymousRateIdHeader: 'X-Anonymous-Client-Id',
    anonymousGateUnavailableError: 'anonymousGateUnavailableError',
    missingSlugError: 'missingSlugError',
    anonymousRouteDeniedError: 'anonymousRouteDeniedError',
    anonymousScopeDisabledError: 'anonymousScopeDisabledError',
    anonymousUnknownIdentity: 'anon:unknown',
    openAiTranscribeUrl: 'https://api.openai.example/v1/audio/transcriptions',
    zeroBytes32: 'zeroBytes32',
    slugAliasMismatchError: 'slugAliasMismatchError',
    slugMismatchError: 'slugMismatchError',
    nonceTtlSeconds: 300,
    nonceRateLimitMax: 5,
    nonceRateLimitWindowMs: 60000,
    nonceRateLimitTtlSeconds: 60,
    usedNonceTtlSeconds: 600,
    loginSiweMaxAgeMs: 300000,
    loginSiweFutureSkewMs: 60000,
    tokenTtlSeconds: 86400,
    sessionConfigNotFoundError: 'sessionConfigNotFoundError',
    bootstrapSessionConfigRequiredError: 'bootstrapSessionConfigRequiredError',
  });
  assert.deepEqual(result.defaults, {
    defaultRpcUrl: 'defaultFaucetRpcUrl',
    defaultAmountEth: 'defaultAmountEth',
    defaultThresholdEth: 'defaultThresholdEth',
  });
});
