import {
  buildCreateSurveyAiPromptModelLabelPatch,
  buildCreateSurveyAddingQuestionTypePatch,
  buildCreateSurveyAutoGeneratedDraftPatch,
  buildCreateSurveyAutoToolTogglePatch,
  buildCreateSurveyBookmarkedQuestionsSetPatch,
  buildCreateSurveyBookmarkedSurveysSetPatch,
  buildCreateSurveyBookmarkSetsPatch,
  buildCreateSurveyCacheLoadedPatch,
  buildCreateSurveyClearFormConfirmPatch,
  buildCreateSurveyClearFormStatePatch,
  buildCreateSurveyCopySuccessPatch,
  buildCreateSurveyDocUrlClearPatch,
  buildCreateSurveyDocUrlErrorPatch,
  buildCreateSurveyDocUrlInputPatch,
  buildCreateSurveyDocumentUrlsPatch,
  buildCreateSurveyFocusTargetPatch,
  buildCreateSurveyHashPatch,
  buildCreateSurveyMountSubmitResetPatch,
  buildCreateSurveyNetworkSwitchPatch,
  buildCreateSurveyOpenLockKeyPatch,
  buildCreateSurveyQuestionListPatch,
  buildCreateSurveyQuestionListValidationPatch,
  buildCreateSurveyQuestionsSubmitSuccessPatch,
  buildCreateSurveySubmitBlockingErrorPatch,
  buildCreateSurveySubmitCatchPatch,
  buildCreateSurveySubmitFailurePatch,
  buildCreateSurveySubmitProgressPatch,
  buildCreateSurveySubmitResetPatch,
  buildCreateSurveySubmitStartPatch,
  buildCreateSurveySurveyLockGateIdsPatch,
  buildCreateSurveySurveySubmitSuccessPatch,
  buildCreateSurveyTitleChangePatch,
  buildCreateSurveyValidationErrorPatch,
} from './createQuestionsAndSurveysHelpers.js';

describe('createQuestionsAndSurveysHelpers state patches', () => {
  it('builds authoring UI state patches', () => {
    expect(buildCreateSurveyCopySuccessPatch('copiedSurveyJson', true)).toEqual({
      copiedSurveyJson: true,
    });
    expect(buildCreateSurveyCopySuccessPatch('copiedSurveyJson', 0)).toEqual({
      copiedSurveyJson: false,
    });
    expect(buildCreateSurveyAiPromptModelLabelPatch('OpenAI gpt-4o')).toEqual({
      aiPromptModelLabel: 'OpenAI gpt-4o',
    });
    expect(buildCreateSurveyAiPromptModelLabelPatch('')).toEqual({
      aiPromptModelLabel: 'Configured model',
    });
    expect(buildCreateSurveyFocusTargetPatch('q1')).toEqual({
      focusTargetUiKey: 'q1',
    });
    expect(buildCreateSurveyFocusTargetPatch()).toEqual({
      focusTargetUiKey: null,
    });
    expect(buildCreateSurveyOpenLockKeyPatch('survey')).toEqual({
      openLockKey: 'survey',
    });
    expect(buildCreateSurveyOpenLockKeyPatch(null)).toEqual({
      openLockKey: '',
    });
  });

  it('builds authoring form status state patches', () => {
    expect(buildCreateSurveyDocUrlInputPatch(' https://example.test/doc ')).toEqual({
      docURLInput: ' https://example.test/doc ',
      docURLError: '',
    });
    expect(buildCreateSurveyDocUrlErrorPatch('Invalid URL')).toEqual({
      docURLError: 'Invalid URL',
    });
    expect(buildCreateSurveyDocUrlClearPatch()).toEqual({
      docURLInput: '',
      docURLError: '',
    });
    expect(buildCreateSurveyDocumentUrlsPatch(['https://example.test/doc'])).toEqual({
      documentURLs: ['https://example.test/doc'],
    });
    expect(buildCreateSurveyTitleChangePatch('New title')).toEqual({
      title: 'New title',
      formValidationError: '',
    });
    expect(buildCreateSurveyAddingQuestionTypePatch('text')).toEqual({
      addingQuestionType: 'text',
    });
    expect(buildCreateSurveyQuestionListPatch([{ id: 'q1' }])).toEqual({
      questions: [{ id: 'q1' }],
    });
    expect(buildCreateSurveyQuestionListValidationPatch([{ id: 'q1' }])).toEqual({
      questions: [{ id: 'q1' }],
      formValidationError: '',
    });
    expect(buildCreateSurveyQuestionListPatch('bad')).toEqual({
      questions: [],
    });
    expect(buildCreateSurveyNetworkSwitchPatch(1)).toEqual({
      needsNetworkSwitch: true,
    });
    expect(buildCreateSurveyClearFormConfirmPatch(false)).toEqual({
      showClearFormConfirm: false,
    });
    expect(buildCreateSurveyValidationErrorPatch('Required')).toEqual({
      formValidationError: 'Required',
    });
    expect(buildCreateSurveyAutoToolTogglePatch({ showAutoTool: true })).toEqual({
      showAutoTool: false,
    });
    expect(buildCreateSurveyAutoToolTogglePatch({ showAutoTool: false })).toEqual({
      showAutoTool: true,
    });
    expect(buildCreateSurveyAutoToolTogglePatch({ showAutoTool: 'open' })).toEqual({
      showAutoTool: false,
    });
    expect(buildCreateSurveyCacheLoadedPatch()).toEqual({
      cacheLoaded: true,
      submitStep: 3,
    });
    expect(buildCreateSurveySubmitResetPatch()).toEqual({
      isSubmitting: false,
      progress: 0,
      showSubmitSteps: false,
      submitStep: 0,
    });
    expect(buildCreateSurveySubmitStartPatch()).toEqual({
      isSubmitting: true,
      progress: 0,
      submissionError: '',
      surveyAddedSuccessfully: false,
      questionsAddedSuccessfully: false,
      lastSubmittedSurveyId: '',
      lastSubmittedSurveyArweaveTxId: '',
      showSubmitSteps: true,
      submitStep: 1,
      cacheLoaded: false,
    });
    expect(buildCreateSurveySubmitFailurePatch('Missing gate')).toEqual({
      isSubmitting: false,
      progress: 0,
      submissionError: 'Missing gate',
      showSubmitSteps: false,
      submitStep: 0,
    });
    expect(buildCreateSurveySubmitBlockingErrorPatch('Missing survey ID')).toEqual({
      isSubmitting: false,
      submissionError: 'Missing survey ID',
      showSubmitSteps: false,
      submitStep: 0,
    });
    expect(
      buildCreateSurveyQuestionsSubmitSuccessPatch({
        resetDraft: true,
        uploadedQuestions: [{ questionId: 'q1' }],
      }),
    ).toEqual({
      title: '',
      questions: [],
      documentURLs: [],
      docURLInput: '',
      surveyHash: '',
      submissionError: '',
      questionsAddedSuccessfully: true,
      isSubmitting: false,
      progress: 100,
      uploadedQuestions: [{ questionId: 'q1' }],
      submitStep: 3,
    });
    expect(
      buildCreateSurveyQuestionsSubmitSuccessPatch({
        uploadedQuestions: [{ questionId: 'q2' }],
      }),
    ).toEqual({
      questionsAddedSuccessfully: true,
      isSubmitting: false,
      progress: 100,
      uploadedQuestions: [{ questionId: 'q2' }],
      submitStep: 3,
    });
    expect(
      buildCreateSurveySurveySubmitSuccessPatch({
        resetDraft: true,
        surveyArweaveTxId: 'tx-1',
        surveyId: 'survey-1',
      }),
    ).toEqual({
      title: '',
      questions: [],
      documentURLs: [],
      docURLInput: '',
      surveyHash: '',
      submissionError: '',
      uploadedQuestions: [],
      surveyAddedSuccessfully: true,
      lastSubmittedSurveyId: 'survey-1',
      lastSubmittedSurveyArweaveTxId: 'tx-1',
      isSubmitting: false,
      progress: 100,
      submitStep: 3,
    });
    expect(
      buildCreateSurveySurveySubmitSuccessPatch({
        surveyArweaveTxId: 'tx-2',
        surveyId: 'survey-2',
      }),
    ).toEqual({
      surveyAddedSuccessfully: true,
      lastSubmittedSurveyId: 'survey-2',
      lastSubmittedSurveyArweaveTxId: 'tx-2',
      isSubmitting: false,
      progress: 100,
      submitStep: 3,
    });
    expect(
      buildCreateSurveySubmitCatchPatch({
        errorMessage: 'Failed',
        shouldResetSubmitProgress: false,
        showSubmitSteps: true,
        submitStep: 0,
      }),
    ).toEqual({
      isSubmitting: false,
      progress: 0,
      submissionError: 'Failed',
      showSubmitSteps: true,
      submitStep: 1,
    });
    expect(
      buildCreateSurveySubmitCatchPatch({
        errorMessage: 'Failed',
        shouldResetSubmitProgress: true,
        showSubmitSteps: true,
        submitStep: 2,
      }),
    ).toEqual({
      isSubmitting: false,
      progress: 0,
      submissionError: 'Failed',
      showSubmitSteps: false,
      submitStep: 0,
    });
    expect(
      buildCreateSurveyAutoGeneratedDraftPatch({
        documentURLs: ['https://example.test/doc'],
        focusTargetUiKey: 'auto-1',
        questions: [{ id: 'q1' }],
        title: 'Generated title',
      }),
    ).toEqual({
      questions: [{ id: 'q1' }],
      documentURLs: ['https://example.test/doc'],
      docURLInput: '',
      docURLError: '',
      formValidationError: '',
      isStandaloneQuestion: false,
      title: 'Generated title',
      showAutoTool: false,
      surveyAddedSuccessfully: false,
      questionsAddedSuccessfully: false,
      submissionError: '',
      lastSubmittedSurveyId: '',
      lastSubmittedSurveyArweaveTxId: '',
      focusTargetUiKey: 'auto-1',
    });
    expect(buildCreateSurveySurveyLockGateIdsPatch(['gate-a'])).toEqual({
      surveyLockGateIds: ['gate-a'],
    });
    expect(buildCreateSurveyClearFormStatePatch()).toEqual({
      title: '',
      questions: [],
      documentURLs: [],
      docURLInput: '',
      surveyHash: '',
      isStandaloneQuestion: true,
      surveyLockGateIds: [],
      openLockKey: '',
      surveyAddedSuccessfully: false,
      questionsAddedSuccessfully: false,
      isSubmitting: false,
      submissionError: '',
      lastSubmittedSurveyId: '',
      lastSubmittedSurveyArweaveTxId: '',
      showClearFormConfirm: false,
      docURLError: '',
      formValidationError: '',
    });
    expect(buildCreateSurveyMountSubmitResetPatch()).toEqual({
      isSubmitting: false,
      progress: 0,
      submissionError: '',
    });
    expect(buildCreateSurveySubmitProgressPatch({ progress: 60, submitStep: 2 })).toEqual({
      progress: 60,
      submitStep: 2,
    });
    expect(buildCreateSurveyHashPatch(null)).toEqual({
      surveyHash: '',
    });
  });

  it('builds normalized authoring bookmark set patches', () => {
    expect(
      buildCreateSurveyBookmarkSetsPatch({
        surveys: ['SurveyA'],
        questions: ['QuestionA'],
      }),
    ).toEqual({
      bookmarkedSurveysSet: new Set(['surveya']),
      bookmarkedQuestionsSet: new Set(['questiona']),
    });

    const questions = new Set(['q1']);
    const patch = buildCreateSurveyBookmarkedQuestionsSetPatch(questions);
    expect(patch).toEqual({
      bookmarkedQuestionsSet: new Set(['q1']),
    });
    expect(patch.bookmarkedQuestionsSet).not.toBe(questions);
    expect(buildCreateSurveyBookmarkedSurveysSetPatch(['S1'])).toEqual({
      bookmarkedSurveysSet: new Set(['s1']),
    });
  });
});
