/** @file surveyToolUtils.js */

export {
  buildQuestionCacheHydrationPatch,
  buildQuestionResponseHydrationPatch,
  buildRatingEnvelopeQidSetFromUserAnswers,
  clampSliderValue,
  getConvictionFromResponse,
  getConvictionFromSlice,
  getConvictionFromSliceStrict,
  getImportanceFromResponse,
  getImportanceFromSlice,
  getNormalizedUiRatingValue,
  isSingleSelectMultichoice,
  normalizeMultichoiceValue,
  toNumberOrNull,
} from './surveyToolResponseState.js';
export { areEnvelopesEquivalent, mergeDecryptedViewedResponse } from './surveyToolResponseMerge.js';
export {
  buildQuestionIdScopeSignature,
  buildRenderedIdsSignature,
  buildSliceToken,
  buildSurveyResponseSliceSignature,
  normalizeQuestionIdKey,
} from './surveyToolSignatures.js';
export {
  areQuestionPayloadsEquivalent,
  canUseRecentQuestionPayloadForAccount,
  ensureQuestionsNet,
  ensureSurveysNet,
  hasCacheHydratedFlag,
  isIncomingResponseMetaNewer,
  mergeQuestionResponses,
  mergeSurveyToolCachePatchIntoSurveysCache,
  mergeSurveyResponsePayloads,
  readQuestionsCache,
  readQuestionsCacheAsync,
  readQuestionsCacheRef,
  readRecentQuestionPayload,
  readSurveysCache,
  readSurveysCacheAsync,
  readSurveysCacheRef,
  stampResponsePayloadWithMeta,
  toResponseRecencyMeta,
  writeQuestionsCache,
  writeSurveysCache,
} from './surveyToolCacheState.js';
export {
  buildSliderModeStatePatch,
  buildSliderPersistOptions,
  getQuestionConvictionSliderValue,
  getQuestionImportanceSliderValue,
  getQuestionSliderMode,
  normalizeSliderMode,
  shouldExpandSliderToggle,
} from './surveyToolSliderState.js';
export {
  appendExplicitSessionHintToPath,
  applyExistingGroupPrefix,
  hasExplicitSessionQueryPinInPath,
  readPathSearch,
} from './surveyToolNavigation.js';
export { resolveSlugForIds } from './surveyToolSlugLookup.js';
export {
  buildDraftAnswersByQuestionId,
  buildDraftHydrationPatchForQuestion,
  buildPersistedDraftQuestionRemovalPlan,
  buildPersistedDraftTrackingAfterLoad,
  buildPersistedDraftTrackingAfterScopedDelete,
  buildPersistedDraftTrackingAfterWrite,
  buildPersistedDraftTrackingClearedState,
  buildPersistedDraftTrackingOnKeyChange,
  buildPersistedDraftWritePlan,
  buildPersistDraftAllowedQuestionIds,
  loadPreviousPersistedDraftSnapshot,
  parsePersistedDraftStorageValue,
  buildSurveyDraftLoadPlan,
  buildPersistedDraftPayload,
  buildPersistedDraftMapsForAllowedIds,
  buildPersistedDraftQuestionEntry,
  removeQuestionFromPersistedDraftPayload,
  buildSurveyDraftCompatScope,
  buildSurveyDraftStorageKey,
  buildSurveyDraftStorageVariantKeys,
  buildSurveyDraftSemanticSignature,
  computeSubmitLabel,
  getPendingStatsSnapshotFromState,
  hasConvictionOrImportanceValueForQuestion,
  hasMeaningfulFieldValue,
  mergePersistedDraftPayloads,
  shouldAutoEncryptAdditionalOnAudienceChange,
  shouldEncryptResponseFieldForSubmit,
  shouldForceOverwriteDraftValues,
  shouldRenderInlineSubmitButton,
  shouldRenderSubmittedIndicator,
  shouldShowSingleQuestionResponseLookupSpinner,
  updateSubmittedSinceLastEdit,
} from './surveyToolDraftState.js';
export {
  buildCacheHydrationSlice,
  buildDraftHydrationUpdatePlan,
  shouldSkipDraftHydrationRun,
  buildDraftHydrationSeedContext,
  buildDraftHydrationRunPlan,
  resolveLocalCacheSliceLookup,
  buildDraftHydrationRenderedQuestionIds,
  buildDraftHydrationOverwriteDecision,
  buildDraftAwareCacheHydrationState,
  buildDraftHydrationState,
  buildHydratedResponseSlice,
  buildExitEditingStatePatch,
  buildInitializedSurveyResponseState,
  buildLocalCacheRehydrationUpdatePlan,
  buildRevertPendingStatePatch,
  buildStartFreshSurveyState,
  loadLocalCacheHydrationSlice,
  prepareLocalCacheRehydrateRun,
  buildResetFormStatePatch,
  buildLocalCacheHydrationMemoKey,
  prepareLocalCacheSliceBuild,
  buildMergedSurveyResponseState,
  buildMergedHydrationQuestionResponses,
  buildLocalCacheRehydrationState,
  buildPrefilledSingleQuestionState,
  buildPrefilledSingleQuestionUpdatePlan,
  buildPrefilledSurveyState,
  buildPrefilledSurveyUpdatePlan,
  loadDraftAnswersByQuestionIdSafely,
  applyResetFormStateEffects,
  applyRevertPendingEffects,
  applyStartFreshEffects,
  applyDraftHydrationEffects,
  applyPrefillUpdatePlan,
  applyLocalCacheRehydrateUpdatePlan,
  applyPrefillStateEffects,
  applyLocalCacheRehydrateMissEffects,
  applyLocalCacheRehydrateNoChangeEffects,
  applyLocalCacheRehydrateAppliedEffects,
  applyLocalCacheRehydrateSuccessEffects,
  runPriorResponseBackfillAttempt,
  applyPriorResponseFetchSuccessEffects,
  buildPriorResponseFetchPlan,
  clearPriorResponseAttemptedKeys,
  executePriorResponseFetchPlan,
  buildGroupedRenderedResponseScopePlan,
  buildLocalCacheHydrationSignature,
  resolveLocalCacheHydrationSignatureLookup,
  loadMissingResponseIdsForScope,
  loadGroupedMissingResponseRequests,
  trackPriorResponseAttemptedKeys,
  buildMissingRenderedResponseResult,
  loadMissingRenderedResponseInfo,
  resolveMissingRenderedResponseLookup,
  buildMissingResponseIdsForRenderedQuestions,
  buildNormalizedRenderedQuestionIds,
  buildQuestionSlugMapForIds,
  resolveQuestionSlugMapLookup,
  buildRevertedResponseSlice,
  buildSubmissionGroupContext,
  buildSurveyResponseStateArray,
  resolveExitEditingBaselineSlice,
  resolveRevertPendingBaselineSlice,
  shouldBackfillPriorResponses,
  shouldHandleStartFresh,
} from './surveyToolHydrationFlow.js';
export {
  buildQuestionScanProgressDisplay,
  doesQuestionProgressMatchSlug,
  formatQuestionScanBlockCount,
  isSurveyToolFilterStateActive,
  normalizeQuestionProgressSlug,
  normalizeSurveyToolFilterState,
  serializeSurveyToolFilterState,
  shouldShowPileFullLoadingState,
} from './surveyToolViewState.js';
export {
  buildQuestionCountScopeContextKey,
  buildQuestionDashboardLoadContextSignature,
  buildQuestionFilterStorageKeyPrefix,
  dedupeQuestionReadSlugs,
  getActiveSessionSlugFromProps,
  getBlockedQuestionIdsSet,
  getExtraQuestionReadSlugs,
  getHighlightedQuestionIdsSet,
  getSessionSlugHintFromProps,
  getSessionSlugPinnedFromProps,
  normalizeSessionSlugValue,
  resolveCurrentTagSessionSlug,
  resolveDecryptHydrationContext,
  resolveDraftSessionContext,
  resolveDraftStorageContext,
  resolveEffectiveSlug,
  resolveEnsureQuestionCachedContext,
  resolveExplicitSessionContext,
  resolveIdLookupContext,
  resolveLockAudienceSessionNameContext,
  resolvePileFilterContext,
  resolvePileLoadContext,
  resolvePileResponseReadContext,
  resolvePileWarmSeedContext,
  resolveQuestionBootstrapContext,
  resolveQuestionCountContext,
  resolveQuestionPayloadCacheWriteContext,
  resolveQuestionReadCacheContext,
  resolveQuestionsDashboardLoadContext,
  resolveResponseHydrationContext,
  resolveResponseJsonContext,
  resolveSubmittedCacheWriteContext,
  resolveSurveyReadContext,
  resolveUpdateCacheContext,
  shouldInheritResolvedTagSessionScope,
} from './surveyToolScope.js';
export {
  bumpSurveyPerfCounter,
  DEBUG_PREFILL,
  EMPTY_QUESTION_POOL,
  GATE_SBT_HYDRATION_RETRY_MS,
  isSurveyPerfCountersEnabled,
  QUESTION_TAG_DROPDOWN_ROW_STYLE,
  scheduleMicrotask,
  SHOW_PILE_HOLOGRAM_TOGGLE,
  surveyLog,
} from './surveyToolRuntimeSupport.js';
